In [1]:
import geopandas as gpd

print("GeoPandas:", gpd.__version__)

GeoPandas: 1.2.0

In [2]:
from pathlib import Path

LGU_DIR = Path("../../../data/raw/lgu_boundaries")

print("Directory:", LGU_DIR.resolve())
print("Exists:", LGU_DIR.exists())

files = sorted(LGU_DIR.glob("*.geojson"))

print(f"\nFound {len(files)} GeoJSON files:")

for file in files:
    print("-", file.name)

Directory: /mnt/c/Users/allea/Downloads/Ahon Pipeline/AHON-Pipeline/data/raw/lgu_boundaries
Exists: True

Found 4 GeoJSON files:
- component_cities.geojson
- highly_urbanized_cities.geojson
- independent_component_cities.geojson
- municipalities.geojson

In [3]:
import geopandas as gpd

for file in files:
    gdf = gpd.read_file(file)

    print("\n" + "=" * 70)
    print("FILE:", file.name)
    print("Rows:", len(gdf))
    print("Columns:", gdf.columns.tolist())
    print("CRS:", gdf.crs)

    print("\nGeometry types:")
    print(gdf.geometry.geom_type.value_counts())

    print("\nFirst 3 rows:")
    display(gdf.head(3))

======================================================================
FILE: component_cities.geojson
Rows: 110
Columns: ['ADM3_EN', 'ADM3_PCODE', 'ADM2_EN', 'ADM2_PCODE', 'ADM1_EN', 'ADM1_PCODE', 'ADM0_EN', 'ADM0_PCODE', 'date', 'validOn', 'validTo', 'ADM3_REF', 'ADM3ALT1EN', 'Shape_Leng', 'Shape_Area', 'AREA_SQKM', 'psgc_id', 'psgc_code', 'psgc_name', 'psgc_status', 'match_confidence', 'psgc_type', 'match_method', 'geometry']
CRS: EPSG:4326

Geometry types:
Polygon         86
MultiPolygon    24
Name: count, dtype: int64

First 3 rows:

,ADM3_EN,ADM3_PCODE,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,date,validOn,...,Shape_Area,AREA_SQKM,psgc_id,psgc_code,psgc_name,psgc_status,match_confidence,psgc_type,match_method,geometry
0,City of Batac,PH0102805,Ilocos Norte,PH01028,Region I (Ilocos Region),PH01,Philippines (the),PH,2022-11-09,2023-11-06,...,0.013493,158.123132,PH0102805,0102805000,City of Batac,matched,1.0,component_city,exact,"POLYGON ((120.61242 18.10947, 120.6221 18.0819..."
1,Laoag City (Capital),PH0102812,Ilocos Norte,PH01028,Region I (Ilocos Region),PH01,Philippines (the),PH,2022-11-09,2023-11-06,...,0.009399,110.056244,PH0102812,0102812000,City of Laoag,matched,1.0,component_city,exact,"POLYGON ((120.59393 18.23292, 120.64356 18.207..."
2,City of Candon,PH0102906,Ilocos Sur,PH01029,Region I (Ilocos Region),PH01,Philippines (the),PH,2022-11-09,2023-11-06,...,0.006589,77.575193,PH0102906,0102906000,City of Candon,matched,1.0,component_city,exact,"POLYGON ((120.42066 17.2324, 120.475 17.23338,..."

======================================================================
FILE: highly_urbanized_cities.geojson
Rows: 34
Columns: ['ADM3_EN', 'ADM3_PCODE', 'ADM2_EN', 'ADM2_PCODE', 'ADM1_EN', 'ADM1_PCODE', 'ADM0_EN', 'ADM0_PCODE', 'date', 'validOn', 'validTo', 'ADM3_REF', 'ADM3ALT1EN', 'Shape_Leng', 'Shape_Area', 'AREA_SQKM', 'psgc_id', 'psgc_code', 'psgc_name', 'psgc_status', 'match_confidence', 'psgc_type', 'match_method', 'namria_adm2_pcode', 'region', 'province', 'geometry']
CRS: EPSG:4326

Geometry types:
Polygon         25
MultiPolygon     9
Name: count, dtype: int64

First 3 rows:

,ADM3_EN,ADM3_PCODE,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,date,validOn,...,psgc_code,psgc_name,psgc_status,match_confidence,psgc_type,match_method,namria_adm2_pcode,region,province,geometry
0,Angeles City,PH0305401,Pampanga,PH03054,Region III (Central Luzon),PH03,Philippines (the),PH,2022-11-09,2023-11-06,...,0330100000,City of Angeles,matched,1.0,highly_urbanized_city,exact,PH03054,Region III (Central Luzon),None,"POLYGON ((120.58261 15.17037, 120.64266 15.178..."
1,Olongapo City,PH0307107,Zambales,PH03071,Region III (Central Luzon),PH03,Philippines (the),PH,2022-11-09,2023-11-06,...,0331400000,City of Olongapo,matched,1.0,highly_urbanized_city,exact,PH03071,Region III (Central Luzon),None,"MULTIPOLYGON (((120.34618 14.86053, 120.3363 1..."
2,Lucena City (Capital),PH0405624,Quezon,PH04056,Region IV-A (Calabarzon),PH04,Philippines (the),PH,2022-11-09,2023-11-06,...,0431200000,City of Lucena,matched,1.0,highly_urbanized_city,exact,PH04056,Region IV-A (CALABARZON),None,"POLYGON ((121.61511 13.99011, 121.65292 13.967..."

======================================================================
FILE: independent_component_cities.geojson
Rows: 6
Columns: ['ADM3_EN', 'ADM3_PCODE', 'ADM2_EN', 'ADM2_PCODE', 'ADM1_EN', 'ADM1_PCODE', 'ADM0_EN', 'ADM0_PCODE', 'date', 'validOn', 'validTo', 'ADM3_REF', 'ADM3ALT1EN', 'Shape_Leng', 'Shape_Area', 'ADM2ALT1EN', 'AREA_SQKM', 'psgc_id', 'psgc_code', 'psgc_name', 'psgc_status', 'match_confidence', 'psgc_type', 'match_method', 'namria_adm2_pcode', 'region', 'province', 'geometry']
CRS: EPSG:4326

Geometry types:
Polygon         5
MultiPolygon    1
Name: count, dtype: int64

First 3 rows:

,ADM3_EN,ADM3_PCODE,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,date,validOn,...,psgc_code,psgc_name,psgc_status,match_confidence,psgc_type,match_method,namria_adm2_pcode,region,province,geometry
0,NaN,NaN,City of Isabela (not a province),PH09097,Region IX (Zamboanga Peninsula),PH09,Philippines (the),PH,2022-11-09,2023-11-06,...,0990100000,City of Isabela (not a province),matched,1.0,independent_component_city,exact,NaN,NaN,None,"MULTIPOLYGON (((121.99131 6.74623, 121.97647 6..."
1,Dagupan City,PH0105518,Pangasinan,PH01055,Region I (Ilocos Region),PH01,Philippines (the),PH,2022-11-09,2023-11-06,...,0105518000,City of Dagupan,matched,1.0,independent_component_city,exact,PH01055,Region I (Ilocos Region),None,"POLYGON ((120.38074 16.09601, 120.3653 16.0899..."
2,City of Santiago,PH0203135,Isabela,PH02031,Region II (Cagayan Valley),PH02,Philippines (the),PH,2022-11-09,2023-11-06,...,0203135000,City of Santiago,matched,1.0,independent_component_city,exact,PH02031,Region II (Cagayan Valley),None,"POLYGON ((121.5789 16.7564, 121.61163 16.68053..."

======================================================================
FILE: municipalities.geojson
Rows: 1485
Columns: ['ADM3_EN', 'ADM3_PCODE', 'ADM2_EN', 'ADM2_PCODE', 'ADM1_EN', 'ADM1_PCODE', 'ADM0_EN', 'ADM0_PCODE', 'date', 'validOn', 'validTo', 'ADM3_REF', 'ADM3ALT1EN', 'Shape_Leng', 'Shape_Area', 'AREA_SQKM', 'psgc_id', 'psgc_code', 'psgc_name', 'psgc_status', 'match_confidence', 'psgc_type', 'match_method', 'geometry']
CRS: EPSG:4326

Geometry types:
Polygon         1154
MultiPolygon     331
Name: count, dtype: int64

First 3 rows:

,ADM3_EN,ADM3_PCODE,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,date,validOn,...,Shape_Area,AREA_SQKM,psgc_id,psgc_code,psgc_name,psgc_status,match_confidence,psgc_type,match_method,geometry
0,Adams,PH0102801,Ilocos Norte,PH01028,Region I (Ilocos Region),PH01,Philippines (the),PH,2022-11-09,2023-11-06,...,0.009506,111.143026,PH0102801,0102801000,Adams,matched,1.0,municipality,exact,"POLYGON ((120.96915 18.51012, 120.94704 18.420..."
1,Bacarra,PH0102802,Ilocos Norte,PH01028,Region I (Ilocos Region),PH01,Philippines (the),PH,2022-11-09,2023-11-06,...,0.004725,55.303195,PH0102802,0102802000,Bacarra,matched,1.0,municipality,exact,"POLYGON ((120.66821 18.28705, 120.6581 18.2776..."
2,Badoc,PH0102803,Ilocos Norte,PH01028,Region I (Ilocos Region),PH01,Philippines (the),PH,2022-11-09,2023-11-06,...,0.006880,80.683970,PH0102803,0102803000,Badoc,matched,1.0,municipality,exact,"POLYGON ((120.47814 17.97717, 120.48312 17.953..."

In [4]:
import geopandas as gpd
import pandas as pd

summary = []

for file in files:
    gdf = gpd.read_file(file)

    summary.append({
        "file": file.name,
        "rows": len(gdf),
        "crs": str(gdf.crs),
        "geometry_types": ", ".join(
            gdf.geometry.geom_type.unique()
        ),
        "missing_psgc_code": gdf["psgc_code"].isna().sum(),
        "duplicate_psgc_code": gdf["psgc_code"].duplicated().sum(),
        "matched": (gdf["psgc_status"] == "matched").sum(),
        "match_confidence_1": (gdf["match_confidence"] == 1.0).sum(),
    })

summary_df = pd.DataFrame(summary)

display(summary_df)

,file,rows,crs,geometry_types,missing_psgc_code,duplicate_psgc_code,matched,match_confidence_1
0,component_cities.geojson,110,EPSG:4326,"Polygon, MultiPolygon",0,0,110,110
1,highly_urbanized_cities.geojson,34,EPSG:4326,"Polygon, MultiPolygon",1,0,31,33
2,independent_component_cities.geojson,6,EPSG:4326,"MultiPolygon, Polygon",0,0,6,6
3,municipalities.geojson,1485,EPSG:4326,"Polygon, MultiPolygon",0,9,1467,1485

In [5]:
municipalities = gpd.read_file(
    LGU_DIR / "municipalities.geojson"
)

duplicate_municipalities = municipalities[
    municipalities["psgc_code"].duplicated(
        keep=False
    )
].sort_values("psgc_code")

display(
    duplicate_municipalities[
        [
            "psgc_code",
            "psgc_name",
            "ADM3_EN",
            "psgc_status",
            "match_confidence",
            "match_method",
            "geometry",
        ]
    ]
)

,psgc_code,psgc_name,ADM3_EN,psgc_status,match_confidence,match_method,geometry
1454,1908706000,Kabuntalan,Kabuntalan (Tumbao),fuzzy,1.0,fuzzy,"POLYGON ((124.32605 7.17916, 124.34894 7.16758..."
1460,1908706000,Kabuntalan,Northern Kabuntalan,fuzzy,1.0,fuzzy,"POLYGON ((124.44432 7.23617, 124.45057 7.2305,..."
1452,1908711000,Sultan Mastura,Parang,matched,1.0,exact,"MULTIPOLYGON (((124.34805 7.38683, 124.35953 7..."
1458,1908711000,Sultan Mastura,Sultan Mastura,fuzzy,1.0,fuzzy,"POLYGON ((124.23975 7.26895, 124.22588 7.29317..."
1453,1908712000,Talitay,Sultan Kudarat (Nuling),matched,1.0,exact,"MULTIPOLYGON (((124.39602 7.35539, 124.36641 7..."
1457,1908712000,Talitay,Talitay,fuzzy,1.0,fuzzy,"POLYGON ((124.4069 7.0638, 124.39236 7.04471, ..."
1461,1908801000,Ampatuan,Ampatuan,matched,1.0,exact,"POLYGON ((124.51314 6.75598, 124.51616 6.72792..."
1475,1908801000,Ampatuan,Datu Saudi-Ampatuan,fuzzy,1.0,fuzzy,"POLYGON ((124.47883 6.97332, 124.43862 6.92695..."
1482,1908801000,Ampatuan,Datu Hoffer Ampatuan,fuzzy,1.0,fuzzy,"POLYGON ((124.42883 6.87518, 124.41525 6.87514..."
1462,1908803000,Datu Abdullah Sangki,Buluan,matched,1.0,exact,"POLYGON ((124.82827 6.75459, 124.84998 6.71716..."
1477,1908803000,Datu Abdullah Sangki,Datu Abdullah Sangki,fuzzy,1.0,fuzzy,"POLYGON ((124.56708 6.86367, 124.58075 6.85117..."
1465,1908808000,Datu Salibo,Shariff Aguak (Maganoy) (Capital),matched,1.0,exact,"POLYGON ((124.48638 6.86791, 124.47507 6.86559..."
1483,1908808000,Datu Salibo,Datu Salibo,fuzzy,1.0,fuzzy,"POLYGON ((124.52446 6.99173, 124.51523 6.98094..."
1466,1908810000,Datu Unsay,Pagalungan,matched,1.0,exact,"MULTIPOLYGON (((124.71735 7.13676, 124.70897 7..."
1476,1908810000,Datu Unsay,Datu Unsay,fuzzy,1.0,fuzzy,"POLYGON ((124.42883 6.87518, 124.42916 6.88726..."
1470,1908819000,Rajah Buayan,Gen. S.K. Pendatun,matched,1.0,exact,"POLYGON ((124.80411 6.88234, 124.82764 6.85957..."
1478,1908819000,Rajah Buayan,Rajah Buayan,fuzzy,1.0,fuzzy,"POLYGON ((124.56708 6.86367, 124.54218 6.86741..."

In [6]:
huc = gpd.read_file(
    LGU_DIR / "highly_urbanized_cities.geojson"
)

missing_huc_psgc = huc[
    huc["psgc_code"].isna()
]

display(
    missing_huc_psgc[
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "ADM2_EN",
            "ADM1_EN",
            "psgc_code",
            "psgc_name",
            "psgc_status",
            "match_confidence",
            "match_method",
        ]
    ]
)

,ADM3_EN,ADM3_PCODE,ADM2_EN,ADM1_EN,psgc_code,psgc_name,psgc_status,match_confidence,match_method
10,City of Isabela,PH0909701,City of Isabela (not a province),Region IX (Zamboanga Peninsula),NaN,NaN,mapped-no-psgc,NaN,huc_map

In [7]:
unmatched_huc = huc[
    huc["psgc_status"] != "matched"
]

display(
    unmatched_huc[
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "psgc_code",
            "psgc_name",
            "psgc_status",
            "match_confidence",
            "match_method",
        ]
    ]
)

,ADM3_EN,ADM3_PCODE,psgc_code,psgc_name,psgc_status,match_confidence,match_method
6,Lapu-Lapu City (Opon),PH0702226,0731100000,City of Lapu-Lapu,fuzzy,1.0,fuzzy
10,City of Isabela,PH0909701,NaN,NaN,mapped-no-psgc,NaN,huc_map
14,General Santos City (Dadiangas),PH1206303,1230800000,City of General Santos,fuzzy,1.0,fuzzy

In [8]:
duplicate_summary = (
    duplicate_municipalities
    .groupby("psgc_code")
    .agg(
        records=("psgc_code", "size"),
        names=("psgc_name", "nunique"),
        geometries=("geometry", "nunique"),
    )
    .reset_index()
)

display(duplicate_summary)

    psgc_code  records  names  geometries
0  1908706000        2      1           2
1  1908711000        2      1           2
2  1908712000        2      1           2
3  1908801000        3      1           3
4  1908803000        2      1           2
5  1908808000        2      1           2
6  1908810000        2      1           2
7  1908819000        2      1           2

In [9]:
duplicate_municipalities[
    [
        "psgc_code",
        "psgc_name",
        "ADM3_EN",
        "ADM3_REF",
        "ADM3ALT1EN",
        "date",
        "validOn",
        "validTo",
        "psgc_status",
        "match_method",
    ]
].sort_values(["psgc_code", "ADM3_EN"])

,psgc_code,psgc_name,ADM3_EN,ADM3_REF,ADM3ALT1EN,date,validOn,validTo,psgc_status,match_method
1454,1908706000,Kabuntalan,Kabuntalan (Tumbao),NaN,Tumbao,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1460,1908706000,Kabuntalan,Northern Kabuntalan,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1452,1908711000,Sultan Mastura,Parang,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1458,1908711000,Sultan Mastura,Sultan Mastura,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1453,1908712000,Talitay,Sultan Kudarat (Nuling),NaN,Nuling,2022-11-09,2023-11-06,None,matched,exact
1457,1908712000,Talitay,Talitay,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1461,1908801000,Ampatuan,Ampatuan,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1482,1908801000,Ampatuan,Datu Hoffer Ampatuan,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1475,1908801000,Ampatuan,Datu Saudi-Ampatuan,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1462,1908803000,Datu Abdullah Sangki,Buluan,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1477,1908803000,Datu Abdullah Sangki,Datu Abdullah Sangki,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1483,1908808000,Datu Salibo,Datu Salibo,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1465,1908808000,Datu Salibo,Shariff Aguak (Maganoy) (Capital),NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1476,1908810000,Datu Unsay,Datu Unsay,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1466,1908810000,Datu Unsay,Pagalungan,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1470,1908819000,Rajah Buayan,Gen. S.K. Pendatun,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1478,1908819000,Rajah Buayan,Rajah Buayan,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy

In [10]:
display(
    duplicate_municipalities[
        [
            "psgc_code",
            "psgc_name",
            "ADM3_EN",
            "ADM3_REF",
            "ADM3ALT1EN",
            "date",
            "validOn",
            "validTo",
            "psgc_status",
            "match_method",
        ]
    ].sort_values(["psgc_code", "ADM3_EN"])
)

,psgc_code,psgc_name,ADM3_EN,ADM3_REF,ADM3ALT1EN,date,validOn,validTo,psgc_status,match_method
1454,1908706000,Kabuntalan,Kabuntalan (Tumbao),NaN,Tumbao,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1460,1908706000,Kabuntalan,Northern Kabuntalan,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1452,1908711000,Sultan Mastura,Parang,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1458,1908711000,Sultan Mastura,Sultan Mastura,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1453,1908712000,Talitay,Sultan Kudarat (Nuling),NaN,Nuling,2022-11-09,2023-11-06,None,matched,exact
1457,1908712000,Talitay,Talitay,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1461,1908801000,Ampatuan,Ampatuan,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1482,1908801000,Ampatuan,Datu Hoffer Ampatuan,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1475,1908801000,Ampatuan,Datu Saudi-Ampatuan,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1462,1908803000,Datu Abdullah Sangki,Buluan,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1477,1908803000,Datu Abdullah Sangki,Datu Abdullah Sangki,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1483,1908808000,Datu Salibo,Datu Salibo,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1465,1908808000,Datu Salibo,Shariff Aguak (Maganoy) (Capital),NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1476,1908810000,Datu Unsay,Datu Unsay,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy
1466,1908810000,Datu Unsay,Pagalungan,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1470,1908819000,Rajah Buayan,Gen. S.K. Pendatun,NaN,NaN,2022-11-09,2023-11-06,None,matched,exact
1478,1908819000,Rajah Buayan,Rajah Buayan,NaN,NaN,2022-11-09,2023-11-06,None,fuzzy,fuzzy

In [11]:
import geopandas as gpd

huc = gpd.read_file(
    LGU_DIR / "highly_urbanized_cities.geojson"
)

In [12]:
city_isabela = huc[
    huc["ADM3_EN"].str.contains("Isabela", case=False, na=False)
]

In [13]:
display(
    city_isabela[
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "ADM2_EN",
            "ADM2_PCODE",
            "ADM1_EN",
            "ADM1_PCODE",
            "ADM0_EN",
            "ADM0_PCODE",
            "ADM3_REF",
            "date",
            "validOn",
            "validTo",
            "psgc_id",
            "psgc_code",
            "psgc_name",
            "psgc_status",
            "match_confidence",
            "match_method",
        ]
    ]
)

,ADM3_EN,ADM3_PCODE,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,ADM3_REF,date,validOn,validTo,psgc_id,psgc_code,psgc_name,psgc_status,match_confidence,match_method
10,City of Isabela,PH0909701,City of Isabela (not a province),PH09097,Region IX (Zamboanga Peninsula),PH09,Philippines (the),PH,NaN,2022-11-09,2023-11-06,None,PH09901,NaN,NaN,mapped-no-psgc,NaN,huc_map

In [14]:
for name, gdf in {
    "municipalities": municipalities,
    "component_cities": component_cities,
    "highly_urbanized_cities": huc,
    "independent_component_cities": independent_component_cities,
}.items():

    print(f"\n{name}")
    print("Invalid geometries:", (~gdf.geometry.is_valid).sum())
    print("Empty geometries:", gdf.geometry.is_empty.sum())
    print("Missing geometries:", gdf.geometry.isna().sum())

NameError: name 'component_cities' is not defined

In [ ]:
invalid_municipalities = municipalities[
    ~municipalities.geometry.is_valid
]

display(
    invalid_municipalities[
        [
            "psgc_code",
            "psgc_name",
            "ADM3_EN",
            "ADM3_PCODE",
            "geometry",
        ]
    ]
)

,psgc_code,psgc_name,ADM3_EN,ADM3_PCODE,geometry
849,0804808000,Laoang,Laoang,PH0804808,"MULTIPOLYGON (((125.06232 12.68605, 125.07422 ..."

In [ ]:
from shapely.validation import explain_validity

laoang = municipalities[
    municipalities["psgc_code"] == "0804808000"
]

for idx, row in laoang.iterrows():
    print("LGU:", row["ADM3_EN"])
    print("PSGC:", row["psgc_code"])
    print("Validity:", row.geometry.is_valid)
    print("Reason:", explain_validity(row.geometry))

LGU: Laoang
PSGC: 0804808000
Validity: False
Reason: Ring Self-intersection[125.057932618 12.4597442780001]

In [ ]:
municipalities_clean = municipalities.copy()

municipalities_clean["geometry"] = (
    municipalities_clean.geometry.make_valid()
)

In [ ]:
laoang_clean = municipalities_clean[
    municipalities_clean["psgc_code"] == "0804808000"
]

for idx, row in laoang_clean.iterrows():
    print("LGU:", row["ADM3_EN"])
    print("PSGC:", row["psgc_code"])
    print("Validity:", row.geometry.is_valid)
    print("Geometry type:", row.geometry.geom_type)

LGU: Laoang
PSGC: 0804808000
Validity: True
Geometry type: MultiPolygon

In [ ]:
print(
    "Invalid geometries:",
    (~municipalities_clean.geometry.is_valid).sum()
)

print(
    "Empty geometries:",
    municipalities_clean.geometry.is_empty.sum()
)

print(
    "Missing geometries:",
    municipalities_clean.geometry.isna().sum()
)

Invalid geometries: 0
Empty geometries: 0
Missing geometries: 0

In [ ]:
duplicate_psgc_summary = (
    municipalities[
        municipalities["psgc_code"].duplicated(keep=False)
    ]
    .groupby("psgc_code")
    .agg(
        records=("psgc_code", "size"),
        psgc_names=("psgc_name", lambda x: list(x.dropna().unique())),
        source_names=("ADM3_EN", lambda x: list(x.dropna().unique())),
        source_refs=("ADM3_REF", lambda x: list(x.dropna().unique())),
        geometries=("geometry", "nunique"),
    )
    .reset_index()
)

display(duplicate_psgc_summary)

,psgc_code,records,psgc_names,source_names,source_refs,geometries
0,1908706000,2,[Kabuntalan],"[Kabuntalan (Tumbao), Northern Kabuntalan]",[],2
1,1908711000,2,[Sultan Mastura],"[Parang, Sultan Mastura]",[],2
2,1908712000,2,[Talitay],"[Sultan Kudarat (Nuling), Talitay]",[],2
3,1908801000,3,[Ampatuan],"[Ampatuan, Datu Saudi-Ampatuan, Datu Hoffer Am...",[],3
4,1908803000,2,[Datu Abdullah Sangki],"[Buluan, Datu Abdullah Sangki]",[],2
5,1908808000,2,[Datu Salibo],"[Shariff Aguak (Maganoy) (Capital), Datu Salibo]",[],2
6,1908810000,2,[Datu Unsay],"[Pagalungan, Datu Unsay]",[],2
7,1908819000,2,[Rajah Buayan],"[Gen. S.K. Pendatun, Rajah Buayan]",[],2

In [ ]:
duplicate_psgc_rows = municipalities[
    municipalities["psgc_code"].duplicated(keep=False)
].copy()

duplicate_psgc_rows["geometry_wkt"] = (
    duplicate_psgc_rows.geometry.to_wkt()
)

display(
    duplicate_psgc_rows[
        [
            "psgc_code",
            "psgc_name",
            "ADM3_EN",
            "ADM3_REF",
            "ADM3ALT1EN",
            "psgc_status",
            "match_method",
            "geometry_wkt",
        ]
    ].sort_values(["psgc_code", "ADM3_EN"])
)

,psgc_code,psgc_name,ADM3_EN,ADM3_REF,ADM3ALT1EN,psgc_status,match_method,geometry_wkt
1454,1908706000,Kabuntalan,Kabuntalan (Tumbao),NaN,Tumbao,fuzzy,fuzzy,"POLYGON ((124.326055 7.17916, 124.348937 7.167..."
1460,1908706000,Kabuntalan,Northern Kabuntalan,NaN,NaN,fuzzy,fuzzy,"POLYGON ((124.444315 7.236166, 124.450566 7.23..."
1452,1908711000,Sultan Mastura,Parang,NaN,NaN,matched,exact,"MULTIPOLYGON (((124.348052 7.386834, 124.35953..."
1458,1908711000,Sultan Mastura,Sultan Mastura,NaN,NaN,fuzzy,fuzzy,"POLYGON ((124.239749 7.268951, 124.22588 7.293..."
1453,1908712000,Talitay,Sultan Kudarat (Nuling),NaN,Nuling,matched,exact,"MULTIPOLYGON (((124.39602 7.355388, 124.366409..."
1457,1908712000,Talitay,Talitay,NaN,NaN,fuzzy,fuzzy,"POLYGON ((124.406896 7.063798, 124.392359 7.04..."
1461,1908801000,Ampatuan,Ampatuan,NaN,NaN,matched,exact,"POLYGON ((124.513137 6.755979, 124.516157 6.72..."
1482,1908801000,Ampatuan,Datu Hoffer Ampatuan,NaN,NaN,fuzzy,fuzzy,"POLYGON ((124.428834 6.875178, 124.415247 6.87..."
1475,1908801000,Ampatuan,Datu Saudi-Ampatuan,NaN,NaN,fuzzy,fuzzy,"POLYGON ((124.478833 6.973323, 124.438619 6.92..."
1462,1908803000,Datu Abdullah Sangki,Buluan,NaN,NaN,matched,exact,"POLYGON ((124.828266 6.754593, 124.849976 6.71..."
1477,1908803000,Datu Abdullah Sangki,Datu Abdullah Sangki,NaN,NaN,fuzzy,fuzzy,"POLYGON ((124.567078 6.863669, 124.580753 6.85..."
1483,1908808000,Datu Salibo,Datu Salibo,NaN,NaN,fuzzy,fuzzy,"POLYGON ((124.524457 6.991726, 124.515233 6.98..."
1465,1908808000,Datu Salibo,Shariff Aguak (Maganoy) (Capital),NaN,NaN,matched,exact,"POLYGON ((124.486382 6.867915, 124.475075 6.86..."
1476,1908810000,Datu Unsay,Datu Unsay,NaN,NaN,fuzzy,fuzzy,"POLYGON ((124.428834 6.875178, 124.429163 6.88..."
1466,1908810000,Datu Unsay,Pagalungan,NaN,NaN,matched,exact,"MULTIPOLYGON (((124.71735 7.136761, 124.708971..."
1470,1908819000,Rajah Buayan,Gen. S.K. Pendatun,NaN,NaN,matched,exact,"POLYGON ((124.804106 6.882345, 124.827641 6.85..."
1478,1908819000,Rajah Buayan,Rajah Buayan,NaN,NaN,fuzzy,fuzzy,"POLYGON ((124.567078 6.863669, 124.54218 6.867..."

In [ ]:
duplicate_reconciliation = (
    municipalities[
        municipalities["psgc_code"].duplicated(keep=False)
    ][
        [
            "psgc_code",
            "psgc_name",
            "ADM3_EN",
            "ADM3_PCODE",
            "ADM3_REF",
            "ADM3ALT1EN",
            "psgc_status",
            "match_method",
            "geometry",
        ]
    ]
    .sort_values(["psgc_code", "ADM3_EN"])
    .copy()
)

display(duplicate_reconciliation.drop(columns="geometry"))

,psgc_code,psgc_name,ADM3_EN,ADM3_PCODE,ADM3_REF,ADM3ALT1EN,psgc_status,match_method
1454,1908706000,Kabuntalan,Kabuntalan (Tumbao),PH1908714,NaN,Tumbao,fuzzy,fuzzy
1460,1908706000,Kabuntalan,Northern Kabuntalan,PH1908734,NaN,NaN,fuzzy,fuzzy
1452,1908711000,Sultan Mastura,Parang,PH1908711,NaN,NaN,matched,exact
1458,1908711000,Sultan Mastura,Sultan Mastura,PH1908724,NaN,NaN,fuzzy,fuzzy
1453,1908712000,Talitay,Sultan Kudarat (Nuling),PH1908712,NaN,Nuling,matched,exact
1457,1908712000,Talitay,Talitay,PH1908721,NaN,NaN,fuzzy,fuzzy
1461,1908801000,Ampatuan,Ampatuan,PH1908801,NaN,NaN,matched,exact
1482,1908801000,Ampatuan,Datu Hoffer Ampatuan,PH1908835,NaN,NaN,fuzzy,fuzzy
1475,1908801000,Ampatuan,Datu Saudi-Ampatuan,PH1908826,NaN,NaN,fuzzy,fuzzy
1462,1908803000,Datu Abdullah Sangki,Buluan,PH1908803,NaN,NaN,matched,exact
1477,1908803000,Datu Abdullah Sangki,Datu Abdullah Sangki,PH1908828,NaN,NaN,fuzzy,fuzzy
1483,1908808000,Datu Salibo,Datu Salibo,PH1908836,NaN,NaN,fuzzy,fuzzy
1465,1908808000,Datu Salibo,Shariff Aguak (Maganoy) (Capital),PH1908808,NaN,NaN,matched,exact
1476,1908810000,Datu Unsay,Datu Unsay,PH1908827,NaN,NaN,fuzzy,fuzzy
1466,1908810000,Datu Unsay,Pagalungan,PH1908810,NaN,NaN,matched,exact
1470,1908819000,Rajah Buayan,Gen. S.K. Pendatun,PH1908819,NaN,NaN,matched,exact
1478,1908819000,Rajah Buayan,Rajah Buayan,PH1908829,NaN,NaN,fuzzy,fuzzy

In [ ]:
psgc_corrections = {
    "Northern Kabuntalan": "1908708000",
    "Parang": "1908709000",
    "Sultan Kudarat (Nuling)": "1908710000",
    "Datu Hoffer Ampatuan": "1908805000",
    "Datu Saudi-Ampatuan": "1908809000",
    "Buluan": "1908802000",
    "Shariff Aguak (Maganoy) (Capital)": "1908820000",
    "Pagalungan": "1908816000",
    "Gen. S.K. Pendatun": "1908811000",
}

In [ ]:
municipalities_reconciled = municipalities.copy()

municipalities_reconciled["canonical_psgc_code"] = (
    municipalities_reconciled["psgc_code"]
)

municipalities_reconciled["reconciliation_status"] = "verified"

In [ ]:
for lgu_name, correct_psgc in psgc_corrections.items():
    mask = municipalities_reconciled["ADM3_EN"] == lgu_name
    municipalities_reconciled.loc[
        mask, "canonical_psgc_code"
    ] = correct_psgc

    municipalities_reconciled.loc[
        mask, "reconciliation_status"
    ] = "corrected_psa_verified"

In [ ]:
duplicates_after_reconciliation = (
    municipalities_reconciled[
        municipalities_reconciled["canonical_psgc_code"]
        .duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

display(
    duplicates_after_reconciliation[
        [
            "canonical_psgc_code",
            "psgc_name",
            "ADM3_EN",
            "psgc_code",
            "reconciliation_status",
        ]
    ]
)

,canonical_psgc_code,psgc_name,ADM3_EN,psgc_code,reconciliation_status
1427,1908709000,Parang,Parang,1906609000,corrected_psa_verified
1451,1908709000,Parang,Matanog,1908709000,verified
1452,1908709000,Sultan Mastura,Parang,1908711000,corrected_psa_verified
1463,1908805000,Datu Hoffer Ampatuan,Datu Paglas,1908805000,verified
1482,1908805000,Ampatuan,Datu Hoffer Ampatuan,1908801000,corrected_psa_verified
1466,1908816000,Datu Unsay,Pagalungan,1908810000,corrected_psa_verified
1468,1908816000,Pagalungan,Talayan,1908816000,verified
1465,1908820000,Datu Salibo,Shariff Aguak (Maganoy) (Capital),1908808000,corrected_psa_verified
1471,1908820000,Shariff Aguak,Mamasapano,1908820000,verified

In [ ]:
affected = municipalities[
    municipalities["psgc_code"].duplicated(keep=False)
].copy()

affected["source_name"] = affected["ADM3_EN"]

display(
    affected[
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "ADM3_REF",
            "ADM3ALT1EN",
            "psgc_code",
            "psgc_name",
            "psgc_status",
            "match_method",
        ]
    ].sort_values("ADM3_EN")
)

,ADM3_EN,ADM3_PCODE,ADM3_REF,ADM3ALT1EN,psgc_code,psgc_name,psgc_status,match_method
1461,Ampatuan,PH1908801,NaN,NaN,1908801000,Ampatuan,matched,exact
1462,Buluan,PH1908803,NaN,NaN,1908803000,Datu Abdullah Sangki,matched,exact
1477,Datu Abdullah Sangki,PH1908828,NaN,NaN,1908803000,Datu Abdullah Sangki,fuzzy,fuzzy
1482,Datu Hoffer Ampatuan,PH1908835,NaN,NaN,1908801000,Ampatuan,fuzzy,fuzzy
1483,Datu Salibo,PH1908836,NaN,NaN,1908808000,Datu Salibo,fuzzy,fuzzy
1475,Datu Saudi-Ampatuan,PH1908826,NaN,NaN,1908801000,Ampatuan,fuzzy,fuzzy
1476,Datu Unsay,PH1908827,NaN,NaN,1908810000,Datu Unsay,fuzzy,fuzzy
1470,Gen. S.K. Pendatun,PH1908819,NaN,NaN,1908819000,Rajah Buayan,matched,exact
1454,Kabuntalan (Tumbao),PH1908714,NaN,Tumbao,1908706000,Kabuntalan,fuzzy,fuzzy
1460,Northern Kabuntalan,PH1908734,NaN,NaN,1908706000,Kabuntalan,fuzzy,fuzzy
1466,Pagalungan,PH1908810,NaN,NaN,1908810000,Datu Unsay,matched,exact
1452,Parang,PH1908711,NaN,NaN,1908711000,Sultan Mastura,matched,exact
1478,Rajah Buayan,PH1908829,NaN,NaN,1908819000,Rajah Buayan,fuzzy,fuzzy
1465,Shariff Aguak (Maganoy) (Capital),PH1908808,NaN,NaN,1908808000,Datu Salibo,matched,exact
1453,Sultan Kudarat (Nuling),PH1908712,NaN,Nuling,1908712000,Talitay,matched,exact
1458,Sultan Mastura,PH1908724,NaN,NaN,1908711000,Sultan Mastura,fuzzy,fuzzy
1457,Talitay,PH1908721,NaN,NaN,1908712000,Talitay,fuzzy,fuzzy

In [ ]:
psgc_reconciliation = {
    "Kabuntalan (Tumbao)": "1908706000",
    "Northern Kabuntalan": "1908708000",
    "Parang": "1908709000",
    "Sultan Mastura": "1908711000",
    "Sultan Kudarat (Nuling)": "1908710000",
    "Talitay": "1908712000",

    "Ampatuan": "1908801000",
    "Buluan": "1908802000",
    "Datu Abdullah Sangki": "1908803000",
    "Datu Hoffer Ampatuan": "1908805000",
    "Datu Salibo": "1908808000",
    "Datu Saudi-Ampatuan": "1908809000",
    "Datu Unsay": "1908810000",
    "Gen. S.K. Pendatun": "1908811000",
    "Pagalungan": "1908816000",
    "Rajah Buayan": "1908819000",
    "Shariff Aguak (Maganoy) (Capital)": "1908820000",
}

In [ ]:
import pandas as pd

psgc_reconciliation = pd.DataFrame([
    {
        "source_lgu_name": "Kabuntalan (Tumbao)",
        "source_admin_code": "PH1908714",
        "source_psgc_code": "1908706000",
        "canonical_lgu_name": "Kabuntalan",
        "canonical_psgc_code": "1908706000",
    },
    {
        "source_lgu_name": "Northern Kabuntalan",
        "source_admin_code": "PH1908734",
        "source_psgc_code": "1908706000",
        "canonical_lgu_name": "Northern Kabuntalan",
        "canonical_psgc_code": "1908708000",
    },
    {
        "source_lgu_name": "Parang",
        "source_admin_code": "PH1908711",
        "source_psgc_code": "1908711000",
        "canonical_lgu_name": "Parang",
        "canonical_psgc_code": "1908709000",
    },
    {
        "source_lgu_name": "Sultan Mastura",
        "source_admin_code": "PH1908724",
        "source_psgc_code": "1908711000",
        "canonical_lgu_name": "Sultan Mastura",
        "canonical_psgc_code": "1908711000",
    },
    {
        "source_lgu_name": "Sultan Kudarat (Nuling)",
        "source_admin_code": "PH1908712",
        "source_psgc_code": "1908712000",
        "canonical_lgu_name": "Sultan Kudarat",
        "canonical_psgc_code": "1908710000",
    },
    {
        "source_lgu_name": "Talitay",
        "source_admin_code": "PH1908721",
        "source_psgc_code": "1908712000",
        "canonical_lgu_name": "Talitay",
        "canonical_psgc_code": "1908712000",
    },
    {
        "source_lgu_name": "Ampatuan",
        "source_admin_code": "PH1908801",
        "source_psgc_code": "1908801000",
        "canonical_lgu_name": "Ampatuan",
        "canonical_psgc_code": "1908801000",
    },
    {
        "source_lgu_name": "Buluan",
        "source_admin_code": "PH1908803",
        "source_psgc_code": "1908803000",
        "canonical_lgu_name": "Buluan",
        "canonical_psgc_code": "1908802000",
    },
    {
        "source_lgu_name": "Datu Abdullah Sangki",
        "source_admin_code": "PH1908828",
        "source_psgc_code": "1908803000",
        "canonical_lgu_name": "Datu Abdullah Sangki",
        "canonical_psgc_code": "1908803000",
    },
    {
        "source_lgu_name": "Datu Hoffer Ampatuan",
        "source_admin_code": "PH1908835",
        "source_psgc_code": "1908801000",
        "canonical_lgu_name": "Datu Hoffer Ampatuan",
        "canonical_psgc_code": "1908805000",
    },
    {
        "source_lgu_name": "Datu Salibo",
        "source_admin_code": "PH1908836",
        "source_psgc_code": "1908808000",
        "canonical_lgu_name": "Datu Salibo",
        "canonical_psgc_code": "1908808000",
    },
    {
        "source_lgu_name": "Datu Saudi-Ampatuan",
        "source_admin_code": "PH1908826",
        "source_psgc_code": "1908801000",
        "canonical_lgu_name": "Datu Saudi-Ampatuan",
        "canonical_psgc_code": "1908809000",
    },
    {
        "source_lgu_name": "Datu Unsay",
        "source_admin_code": "PH1908827",
        "source_psgc_code": "1908810000",
        "canonical_lgu_name": "Datu Unsay",
        "canonical_psgc_code": "1908810000",
    },
    {
        "source_lgu_name": "Gen. S.K. Pendatun",
        "source_admin_code": "PH1908819",
        "source_psgc_code": "1908819000",
        "canonical_lgu_name": "Gen. S.K. Pendatun",
        "canonical_psgc_code": "1908811000",
    },
    {
        "source_lgu_name": "Pagalungan",
        "source_admin_code": "PH1908810",
        "source_psgc_code": "1908810000",
        "canonical_lgu_name": "Pagalungan",
        "canonical_psgc_code": "1908816000",
    },
    {
        "source_lgu_name": "Rajah Buayan",
        "source_admin_code": "PH1908829",
        "source_psgc_code": "1908819000",
        "canonical_lgu_name": "Rajah Buayan",
        "canonical_psgc_code": "1908819000",
    },
    {
        "source_lgu_name": "Shariff Aguak (Maganoy) (Capital)",
        "source_admin_code": "PH1908808",
        "source_psgc_code": "1908808000",
        "canonical_lgu_name": "Shariff Aguak",
        "canonical_psgc_code": "1908820000",
    },
])

In [ ]:
psgc_reconciliation["reconciliation_status"] = (
    psgc_reconciliation.apply(
        lambda row:
            "verified"
            if row["source_psgc_code"] == row["canonical_psgc_code"]
            else "corrected_psa_verified",
        axis=1
    )
)

psgc_reconciliation["reconciliation_source"] = "PSA PSGC"

In [ ]:
display(psgc_reconciliation)

,source_lgu_name,source_admin_code,source_psgc_code,canonical_lgu_name,canonical_psgc_code,reconciliation_status,reconciliation_source
0,Kabuntalan (Tumbao),PH1908714,1908706000,Kabuntalan,1908706000,verified,PSA PSGC
1,Northern Kabuntalan,PH1908734,1908706000,Northern Kabuntalan,1908708000,corrected_psa_verified,PSA PSGC
2,Parang,PH1908711,1908711000,Parang,1908709000,corrected_psa_verified,PSA PSGC
3,Sultan Mastura,PH1908724,1908711000,Sultan Mastura,1908711000,verified,PSA PSGC
4,Sultan Kudarat (Nuling),PH1908712,1908712000,Sultan Kudarat,1908710000,corrected_psa_verified,PSA PSGC
5,Talitay,PH1908721,1908712000,Talitay,1908712000,verified,PSA PSGC
6,Ampatuan,PH1908801,1908801000,Ampatuan,1908801000,verified,PSA PSGC
7,Buluan,PH1908803,1908803000,Buluan,1908802000,corrected_psa_verified,PSA PSGC
8,Datu Abdullah Sangki,PH1908828,1908803000,Datu Abdullah Sangki,1908803000,verified,PSA PSGC
9,Datu Hoffer Ampatuan,PH1908835,1908801000,Datu Hoffer Ampatuan,1908805000,corrected_psa_verified,PSA PSGC
10,Datu Salibo,PH1908836,1908808000,Datu Salibo,1908808000,verified,PSA PSGC
11,Datu Saudi-Ampatuan,PH1908826,1908801000,Datu Saudi-Ampatuan,1908809000,corrected_psa_verified,PSA PSGC
12,Datu Unsay,PH1908827,1908810000,Datu Unsay,1908810000,verified,PSA PSGC
13,Gen. S.K. Pendatun,PH1908819,1908819000,Gen. S.K. Pendatun,1908811000,corrected_psa_verified,PSA PSGC
14,Pagalungan,PH1908810,1908810000,Pagalungan,1908816000,corrected_psa_verified,PSA PSGC
15,Rajah Buayan,PH1908829,1908819000,Rajah Buayan,1908819000,verified,PSA PSGC
16,Shariff Aguak (Maganoy) (Capital),PH1908808,1908808000,Shariff Aguak,1908820000,corrected_psa_verified,PSA PSGC

In [ ]:
display(
    psgc_reconciliation[
        [
            "source_lgu_name",
            "source_admin_code",
            "source_psgc_code",
            "canonical_lgu_name",
            "canonical_psgc_code",
            "reconciliation_status",
            "reconciliation_source",
        ]
    ]
)

,source_lgu_name,source_admin_code,source_psgc_code,canonical_lgu_name,canonical_psgc_code,reconciliation_status,reconciliation_source
0,Kabuntalan (Tumbao),PH1908714,1908706000,Kabuntalan,1908706000,verified,PSA PSGC
1,Northern Kabuntalan,PH1908734,1908706000,Northern Kabuntalan,1908708000,corrected_psa_verified,PSA PSGC
2,Parang,PH1908711,1908711000,Parang,1908709000,corrected_psa_verified,PSA PSGC
3,Sultan Mastura,PH1908724,1908711000,Sultan Mastura,1908711000,verified,PSA PSGC
4,Sultan Kudarat (Nuling),PH1908712,1908712000,Sultan Kudarat,1908710000,corrected_psa_verified,PSA PSGC
5,Talitay,PH1908721,1908712000,Talitay,1908712000,verified,PSA PSGC
6,Ampatuan,PH1908801,1908801000,Ampatuan,1908801000,verified,PSA PSGC
7,Buluan,PH1908803,1908803000,Buluan,1908802000,corrected_psa_verified,PSA PSGC
8,Datu Abdullah Sangki,PH1908828,1908803000,Datu Abdullah Sangki,1908803000,verified,PSA PSGC
9,Datu Hoffer Ampatuan,PH1908835,1908801000,Datu Hoffer Ampatuan,1908805000,corrected_psa_verified,PSA PSGC
10,Datu Salibo,PH1908836,1908808000,Datu Salibo,1908808000,verified,PSA PSGC
11,Datu Saudi-Ampatuan,PH1908826,1908801000,Datu Saudi-Ampatuan,1908809000,corrected_psa_verified,PSA PSGC
12,Datu Unsay,PH1908827,1908810000,Datu Unsay,1908810000,verified,PSA PSGC
13,Gen. S.K. Pendatun,PH1908819,1908819000,Gen. S.K. Pendatun,1908811000,corrected_psa_verified,PSA PSGC
14,Pagalungan,PH1908810,1908810000,Pagalungan,1908816000,corrected_psa_verified,PSA PSGC
15,Rajah Buayan,PH1908829,1908819000,Rajah Buayan,1908819000,verified,PSA PSGC
16,Shariff Aguak (Maganoy) (Capital),PH1908808,1908808000,Shariff Aguak,1908820000,corrected_psa_verified,PSA PSGC

In [ ]:
# Create a working copy — do not modify the Raw dataframe
municipalities_reconciled = municipalities.copy()

# Preserve the original source PSGC
municipalities_reconciled["source_psgc_code"] = (
    municipalities_reconciled["psgc_code"]
)

# Create canonical PSGC initially equal to source PSGC
municipalities_reconciled["canonical_psgc_code"] = (
    municipalities_reconciled["psgc_code"]
)

# Create canonical name initially equal to source name
municipalities_reconciled["canonical_lgu_name"] = (
    municipalities_reconciled["ADM3_EN"]
)

# Default status
municipalities_reconciled["reconciliation_status"] = "source_verified"

In [ ]:
reconciliation_lookup = (
    psgc_reconciliation
    .set_index("source_admin_code")
)

In [ ]:
for source_code, row in reconciliation_lookup.iterrows():

    mask = (
        municipalities_reconciled["ADM3_PCODE"]
        == source_code
    )

    municipalities_reconciled.loc[
        mask, "canonical_psgc_code"
    ] = row["canonical_psgc_code"]

    municipalities_reconciled.loc[
        mask, "canonical_lgu_name"
    ] = row["canonical_lgu_name"]

    municipalities_reconciled.loc[
        mask, "reconciliation_status"
    ] = row["reconciliation_status"]

In [ ]:
display(
    municipalities_reconciled[
        municipalities_reconciled["reconciliation_status"]
        == "corrected_psa_verified"
    ][
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_lgu_name",
            "canonical_psgc_code",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,ADM3_PCODE,source_psgc_code,canonical_lgu_name,canonical_psgc_code,reconciliation_status
1452,Parang,PH1908711,1908711000,Parang,1908709000,corrected_psa_verified
1453,Sultan Kudarat (Nuling),PH1908712,1908712000,Sultan Kudarat,1908710000,corrected_psa_verified
1460,Northern Kabuntalan,PH1908734,1908706000,Northern Kabuntalan,1908708000,corrected_psa_verified
1462,Buluan,PH1908803,1908803000,Buluan,1908802000,corrected_psa_verified
1465,Shariff Aguak (Maganoy) (Capital),PH1908808,1908808000,Shariff Aguak,1908820000,corrected_psa_verified
1466,Pagalungan,PH1908810,1908810000,Pagalungan,1908816000,corrected_psa_verified
1470,Gen. S.K. Pendatun,PH1908819,1908819000,Gen. S.K. Pendatun,1908811000,corrected_psa_verified
1475,Datu Saudi-Ampatuan,PH1908826,1908801000,Datu Saudi-Ampatuan,1908809000,corrected_psa_verified
1482,Datu Hoffer Ampatuan,PH1908835,1908801000,Datu Hoffer Ampatuan,1908805000,corrected_psa_verified

In [ ]:
duplicate_canonical = (
    municipalities_reconciled[
        municipalities_reconciled["canonical_psgc_code"]
        .duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

display(
    duplicate_canonical[
        [
            "ADM3_EN",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1451,Matanog,1908709000,1908709000,Matanog,source_verified
1452,Parang,1908711000,1908709000,Parang,corrected_psa_verified
1463,Datu Paglas,1908805000,1908805000,Datu Paglas,source_verified
1482,Datu Hoffer Ampatuan,1908801000,1908805000,Datu Hoffer Ampatuan,corrected_psa_verified
1466,Pagalungan,1908810000,1908816000,Pagalungan,corrected_psa_verified
1468,Talayan,1908816000,1908816000,Talayan,source_verified
1465,Shariff Aguak (Maganoy) (Capital),1908808000,1908820000,Shariff Aguak,corrected_psa_verified
1471,Mamasapano,1908820000,1908820000,Mamasapano,source_verified

In [ ]:
additional_reconciliation = pd.DataFrame([
    {
        "source_lgu_name": "Matanog",
        "source_admin_code": "PH1908707",
        "source_psgc_code": "1908709000",
        "canonical_lgu_name": "Matanog",
        "canonical_psgc_code": "1908707000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Paglas",
        "source_admin_code": "PH1908806",
        "source_psgc_code": "1908805000",
        "canonical_lgu_name": "Datu Paglas",
        "canonical_psgc_code": "1908806000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Talayan",
        "source_admin_code": "PH1908824",
        "source_psgc_code": "1908816000",
        "canonical_lgu_name": "Talayan",
        "canonical_psgc_code": "1908824000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Mamasapano",
        "source_admin_code": "PH1908813",
        "source_psgc_code": "1908820000",
        "canonical_lgu_name": "Mamasapano",
        "canonical_psgc_code": "1908813000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
])

psgc_reconciliation = pd.concat(
    [psgc_reconciliation, additional_reconciliation],
    ignore_index=True
)

display(additional_reconciliation)

,source_lgu_name,source_admin_code,source_psgc_code,canonical_lgu_name,canonical_psgc_code,reconciliation_status,reconciliation_source
0,Matanog,PH1908707,1908709000,Matanog,1908707000,corrected_psa_verified,PSA PSGC
1,Datu Paglas,PH1908806,1908805000,Datu Paglas,1908806000,corrected_psa_verified,PSA PSGC
2,Talayan,PH1908824,1908816000,Talayan,1908824000,corrected_psa_verified,PSA PSGC
3,Mamasapano,PH1908813,1908820000,Mamasapano,1908813000,corrected_psa_verified,PSA PSGC

In [ ]:
municipalities_reconciled = municipalities.copy()

# Preserve original source PSGC
municipalities_reconciled["source_psgc_code"] = (
    municipalities_reconciled["psgc_code"]
)

# Create lookup from source admin code
reconciliation_lookup = (
    psgc_reconciliation
    .set_index("source_admin_code")
)

# Apply canonical PSGC
municipalities_reconciled["canonical_psgc_code"] = (
    municipalities_reconciled["ADM3_PCODE"]
    .map(reconciliation_lookup["canonical_psgc_code"])
    .fillna(municipalities_reconciled["source_psgc_code"])
)

# Apply canonical LGU name
municipalities_reconciled["canonical_lgu_name"] = (
    municipalities_reconciled["ADM3_PCODE"]
    .map(reconciliation_lookup["canonical_lgu_name"])
    .fillna(municipalities_reconciled["ADM3_EN"])
)

# Apply reconciliation status
municipalities_reconciled["reconciliation_status"] = (
    municipalities_reconciled["ADM3_PCODE"]
    .map(reconciliation_lookup["reconciliation_status"])
    .fillna("source_verified")
)

In [ ]:
new_corrections = municipalities_reconciled[
    municipalities_reconciled["ADM3_EN"].isin([
        "Matanog",
        "Datu Paglas",
        "Talayan",
        "Mamasapano"
    ])
]

display(
    new_corrections[
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1451,Matanog,PH1908709,1908709000,1908709000,Matanog,source_verified
1463,Datu Paglas,PH1908805,1908805000,1908805000,Datu Paglas,source_verified
1468,Talayan,PH1908816,1908816000,1908816000,Talayan,source_verified
1471,Mamasapano,PH1908820,1908820000,1908820000,Mamasapano,source_verified

In [ ]:
duplicate_canonical = (
    municipalities_reconciled[
        municipalities_reconciled["canonical_psgc_code"]
        .duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

display(
    duplicate_canonical[
        [
            "ADM3_EN",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1451,Matanog,1908709000,1908709000,Matanog,source_verified
1452,Parang,1908711000,1908709000,Parang,corrected_psa_verified
1463,Datu Paglas,1908805000,1908805000,Datu Paglas,source_verified
1482,Datu Hoffer Ampatuan,1908801000,1908805000,Datu Hoffer Ampatuan,corrected_psa_verified
1466,Pagalungan,1908810000,1908816000,Pagalungan,corrected_psa_verified
1468,Talayan,1908816000,1908816000,Talayan,source_verified
1465,Shariff Aguak (Maganoy) (Capital),1908808000,1908820000,Shariff Aguak,corrected_psa_verified
1471,Mamasapano,1908820000,1908820000,Mamasapano,source_verified

In [ ]:
print("Total municipality records:", len(municipalities_reconciled))
print(
    "Unique canonical PSGCs:",
    municipalities_reconciled["canonical_psgc_code"].nunique()
)

Total municipality records: 1485
Unique canonical PSGCs: 1481

In [ ]:
print("Total municipality records:", len(municipalities_reconciled))
print(
    "Unique canonical PSGCs:",
    municipalities_reconciled["canonical_psgc_code"].nunique()
)

Total municipality records: 1485
Unique canonical PSGCs: 1481

In [ ]:
LGU_COLUMNS = [
    "ADM3_EN",
    "ADM3_PCODE",
    "source_psgc_code",
    "canonical_psgc_code",
    "canonical_lgu_name",
    "reconciliation_status",
    "geometry",
]

In [ ]:
municipalities_master = municipalities_reconciled[
    LGU_COLUMNS
].copy()

municipalities_master["lgu_type"] = "Municipality"

In [ ]:
def prepare_city_dataset(gdf, lgu_type):
    df = gdf.copy()

    df["source_psgc_code"] = df["psgc_id"]

    df["canonical_psgc_code"] = df["psgc_id"]

    df["canonical_lgu_name"] = df["ADM3_EN"]

    df["reconciliation_status"] = "source_verified"

    df["lgu_type"] = lgu_type

    return df[
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
            "lgu_type",
            "geometry",
        ]
    ]

In [ ]:
component_cities_master = prepare_city_dataset(
    component_cities,
    "Component City"
)

huc_master = prepare_city_dataset(
    huc,
    "Highly Urbanized City"
)

independent_cities_master = prepare_city_dataset(
    independent_component_cities,
    "Independent Component City"
)

In [ ]:
lgu_master = pd.concat(
    [
        municipalities_master,
        component_cities_master,
        huc_master,
        independent_cities_master,
    ],
    ignore_index=True
)

In [ ]:
print("Total LGU boundary records:", len(lgu_master))

Total LGU boundary records: 1635

In [ ]:
display(
    lgu_master["lgu_type"]
    .value_counts()
    .rename_axis("lgu_type")
    .reset_index(name="count")
)

                     lgu_type  count
0                Municipality   1485
1              Component City    110
2       Highly Urbanized City     34
3  Independent Component City      6

In [ ]:
duplicate_lgu_psgc = (
    lgu_master[
        lgu_master["canonical_psgc_code"]
        .duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

display(
    duplicate_lgu_psgc[
        [
            "ADM3_EN",
            "lgu_type",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,lgu_type,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1451,Matanog,Municipality,1908709000,1908709000,Matanog,source_verified
1452,Parang,Municipality,1908711000,1908709000,Parang,corrected_psa_verified
1463,Datu Paglas,Municipality,1908805000,1908805000,Datu Paglas,source_verified
1482,Datu Hoffer Ampatuan,Municipality,1908801000,1908805000,Datu Hoffer Ampatuan,corrected_psa_verified
1466,Pagalungan,Municipality,1908810000,1908816000,Pagalungan,corrected_psa_verified
1468,Talayan,Municipality,1908816000,1908816000,Talayan,source_verified
1465,Shariff Aguak (Maganoy) (Capital),Municipality,1908808000,1908820000,Shariff Aguak,corrected_psa_verified
1471,Mamasapano,Municipality,1908820000,1908820000,Mamasapano,source_verified
1605,City of Isabela,Highly Urbanized City,PH09901,PH09901,City of Isabela,source_verified
1629,NaN,Independent Component City,PH09901,PH09901,NaN,source_verified

In [ ]:
print("Total LGUs:", len(lgu_master))
print(
    "Unique canonical PSGCs:",
    lgu_master["canonical_psgc_code"].nunique()
)

Total LGUs: 1635
Unique canonical PSGCs: 1630

In [ ]:
duplicate_lgu_psgc = (
    lgu_master[
        lgu_master["canonical_psgc_code"]
        .duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

display(
    duplicate_lgu_psgc[
        [
            "ADM3_EN",
            "lgu_type",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,lgu_type,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1451,Matanog,Municipality,1908709000,1908709000,Matanog,source_verified
1452,Parang,Municipality,1908711000,1908709000,Parang,corrected_psa_verified
1463,Datu Paglas,Municipality,1908805000,1908805000,Datu Paglas,source_verified
1482,Datu Hoffer Ampatuan,Municipality,1908801000,1908805000,Datu Hoffer Ampatuan,corrected_psa_verified
1466,Pagalungan,Municipality,1908810000,1908816000,Pagalungan,corrected_psa_verified
1468,Talayan,Municipality,1908816000,1908816000,Talayan,source_verified
1465,Shariff Aguak (Maganoy) (Capital),Municipality,1908808000,1908820000,Shariff Aguak,corrected_psa_verified
1471,Mamasapano,Municipality,1908820000,1908820000,Mamasapano,source_verified
1605,City of Isabela,Highly Urbanized City,PH09901,PH09901,City of Isabela,source_verified
1629,NaN,Independent Component City,PH09901,PH09901,NaN,source_verified

In [ ]:
missing_canonical = lgu_master[
    lgu_master["canonical_psgc_code"].isna()
]

display(
    missing_canonical[
        [
            "ADM3_EN",
            "lgu_type",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
        ]
    ]
)

Empty DataFrame
Columns: [ADM3_EN, lgu_type, source_psgc_code, canonical_psgc_code, canonical_lgu_name]
Index: []

In [ ]:
print(
    "Number of duplicated PSGC records:",
    lgu_master["canonical_psgc_code"].duplicated(keep=False).sum()
)

print(
    "Number of duplicated PSGC values:",
    lgu_master["canonical_psgc_code"].duplicated().sum()
)

Number of duplicated PSGC records: 10
Number of duplicated PSGC values: 5

In [ ]:
psgc_counts = (
    lgu_master["canonical_psgc_code"]
    .value_counts()
)

display(
    psgc_counts[
        psgc_counts > 1
    ].to_frame("record_count")
)

                     record_count
canonical_psgc_code
1908709000                      2
1908805000                      2
1908820000                      2
1908816000                      2
PH09901                         2

In [ ]:
problem_municipalities = municipalities[
    municipalities["ADM3_EN"].isin([
        "Matanog",
        "Datu Paglas",
        "Talayan",
        "Mamasapano"
    ])
]

display(
    problem_municipalities[
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "psgc_id",
            "ADM2_EN",
            "ADM2_PCODE",
            "ADM1_EN",
            "ADM1_PCODE",
        ]
    ]
)

,ADM3_EN,ADM3_PCODE,psgc_id,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE
1451,Matanog,PH1908709,PH1908709,Maguindanao del Norte,PH19087,Bangsamoro Autonomous Region In Muslim Mindana...,PH19
1463,Datu Paglas,PH1908805,PH1908805,Maguindanao del Sur,PH19088,Bangsamoro Autonomous Region In Muslim Mindana...,PH19
1468,Talayan,PH1908816,PH1908816,Maguindanao del Sur,PH19088,Bangsamoro Autonomous Region In Muslim Mindana...,PH19
1471,Mamasapano,PH1908820,PH1908820,Maguindanao del Sur,PH19088,Bangsamoro Autonomous Region In Muslim Mindana...,PH19

In [ ]:
isabela_conflict = lgu_master[
    lgu_master["canonical_psgc_code"] == "PH09901"
]

display(
    isabela_conflict[
        [
            "ADM3_EN",
            "lgu_type",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,lgu_type,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1605,City of Isabela,Highly Urbanized City,PH0909701,PH09901,PH09901,City of Isabela,source_verified
1629,NaN,Independent Component City,NaN,PH09901,PH09901,NaN,source_verified

In [ ]:
psgc_reconciliation = psgc_reconciliation[
    ~psgc_reconciliation["source_lgu_name"].isin([
        "Matanog",
        "Datu Paglas",
        "Talayan",
        "Mamasapano"
    ])
].copy()

In [ ]:
additional_reconciliation = pd.DataFrame([
    {
        "source_lgu_name": "Matanog",
        "source_admin_code": "PH1908709",
        "source_psgc_code": "1908709000",
        "canonical_lgu_name": "Matanog",
        "canonical_psgc_code": "1908707000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Paglas",
        "source_admin_code": "PH1908805",
        "source_psgc_code": "1908805000",
        "canonical_lgu_name": "Datu Paglas",
        "canonical_psgc_code": "1908806000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Talayan",
        "source_admin_code": "PH1908816",
        "source_psgc_code": "1908816000",
        "canonical_lgu_name": "Talayan",
        "canonical_psgc_code": "1908824000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Mamasapano",
        "source_admin_code": "PH1908820",
        "source_psgc_code": "1908820000",
        "canonical_lgu_name": "Mamasapano",
        "canonical_psgc_code": "1908813000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
])

psgc_reconciliation = pd.concat(
    [psgc_reconciliation, additional_reconciliation],
    ignore_index=True
)

In [ ]:
municipalities_reconciled = municipalities.copy()

municipalities_reconciled["source_psgc_code"] = (
    municipalities_reconciled["psgc_code"]
)

reconciliation_lookup = (
    psgc_reconciliation
    .set_index("source_admin_code")
)

municipalities_reconciled["canonical_psgc_code"] = (
    municipalities_reconciled["ADM3_PCODE"]
    .map(reconciliation_lookup["canonical_psgc_code"])
    .fillna(municipalities_reconciled["source_psgc_code"])
)

municipalities_reconciled["canonical_lgu_name"] = (
    municipalities_reconciled["ADM3_PCODE"]
    .map(reconciliation_lookup["canonical_lgu_name"])
    .fillna(municipalities_reconciled["ADM3_EN"])
)

municipalities_reconciled["reconciliation_status"] = (
    municipalities_reconciled["ADM3_PCODE"]
    .map(reconciliation_lookup["reconciliation_status"])
    .fillna("source_verified")
)

In [ ]:
display(
    municipalities_reconciled[
        municipalities_reconciled["ADM3_EN"].isin([
            "Matanog",
            "Datu Paglas",
            "Talayan",
            "Mamasapano"
        ])
    ][
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1451,Matanog,PH1908709,1908709000,1908707000,Matanog,corrected_psa_verified
1463,Datu Paglas,PH1908805,1908805000,1908806000,Datu Paglas,corrected_psa_verified
1468,Talayan,PH1908816,1908816000,1908824000,Talayan,corrected_psa_verified
1471,Mamasapano,PH1908820,1908820000,1908813000,Mamasapano,corrected_psa_verified

In [ ]:
municipalities_master = municipalities_reconciled[
    LGU_COLUMNS
].copy()

municipalities_master["lgu_type"] = "Municipality"

In [ ]:
lgu_master = pd.concat(
    [
        municipalities_master,
        component_cities_master,
        huc_master,
        independent_cities_master,
    ],
    ignore_index=True
)

In [ ]:
duplicate_lgu_psgc = (
    lgu_master[
        lgu_master["canonical_psgc_code"]
        .duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

display(
    duplicate_lgu_psgc[
        [
            "ADM3_EN",
            "lgu_type",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,lgu_type,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1450,Datu Odin Sinsuat (Dinaig),Municipality,PH1908707,1908707000,1908707000,Datu Odin Sinsuat (Dinaig),source_verified
1451,Matanog,Municipality,PH1908709,1908709000,1908707000,Matanog,corrected_psa_verified
1463,Datu Paglas,Municipality,PH1908805,1908805000,1908806000,Datu Paglas,corrected_psa_verified
1464,Datu Piang,Municipality,PH1908806,1908806000,1908806000,Datu Piang,source_verified
1467,Sultan Sa Barongis (Lambayong),Municipality,PH1908813,1908813000,1908813000,Sultan Sa Barongis (Lambayong),source_verified
1471,Mamasapano,Municipality,PH1908820,1908820000,1908813000,Mamasapano,corrected_psa_verified
1605,City of Isabela,Highly Urbanized City,PH0909701,PH09901,PH09901,City of Isabela,source_verified
1629,NaN,Independent Component City,NaN,PH09901,PH09901,NaN,source_verified

In [ ]:
print("Total LGUs:", len(lgu_master))
print(
    "Unique canonical PSGCs:",
    lgu_master["canonical_psgc_code"].nunique()
)

Total LGUs: 1635
Unique canonical PSGCs: 1631

In [ ]:
duplicate_lgu_psgc = (
    lgu_master[
        lgu_master["canonical_psgc_code"]
        .duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

display(
    duplicate_lgu_psgc[
        [
            "ADM3_EN",
            "lgu_type",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,lgu_type,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1450,Datu Odin Sinsuat (Dinaig),Municipality,PH1908707,1908707000,1908707000,Datu Odin Sinsuat (Dinaig),source_verified
1451,Matanog,Municipality,PH1908709,1908709000,1908707000,Matanog,corrected_psa_verified
1463,Datu Paglas,Municipality,PH1908805,1908805000,1908806000,Datu Paglas,corrected_psa_verified
1464,Datu Piang,Municipality,PH1908806,1908806000,1908806000,Datu Piang,source_verified
1467,Sultan Sa Barongis (Lambayong),Municipality,PH1908813,1908813000,1908813000,Sultan Sa Barongis (Lambayong),source_verified
1471,Mamasapano,Municipality,PH1908820,1908820000,1908813000,Mamasapano,corrected_psa_verified
1605,City of Isabela,Highly Urbanized City,PH0909701,PH09901,PH09901,City of Isabela,source_verified
1629,NaN,Independent Component City,NaN,PH09901,PH09901,NaN,source_verified

In [ ]:
new_reconciliation = pd.DataFrame([
    {
        "source_lgu_name": "Datu Odin Sinsuat (Dinaig)",
        "source_admin_code": "PH1908707",
        "source_psgc_code": "1908707000",
        "canonical_lgu_name": "Datu Odin Sinsuat",
        "canonical_psgc_code": "1908705000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Piang",
        "source_admin_code": "PH1908806",
        "source_psgc_code": "1908806000",
        "canonical_lgu_name": "Datu Piang",
        "canonical_psgc_code": "1908807000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Sultan Sa Barongis (Lambayong)",
        "source_admin_code": "PH1908813",
        "source_psgc_code": "1908813000",
        "canonical_lgu_name": "Sultan Sa Barongis",
        "canonical_psgc_code": "1908823000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
])

psgc_reconciliation = pd.concat(
    [psgc_reconciliation, new_reconciliation],
    ignore_index=True
)

In [ ]:
municipalities_reconciled = municipalities.copy()

municipalities_reconciled["source_psgc_code"] = (
    municipalities_reconciled["psgc_code"]
)

reconciliation_lookup = (
    psgc_reconciliation
    .set_index("source_admin_code")
)

municipalities_reconciled["canonical_psgc_code"] = (
    municipalities_reconciled["ADM3_PCODE"]
    .map(reconciliation_lookup["canonical_psgc_code"])
    .fillna(municipalities_reconciled["source_psgc_code"])
)

municipalities_reconciled["canonical_lgu_name"] = (
    municipalities_reconciled["ADM3_PCODE"]
    .map(reconciliation_lookup["canonical_lgu_name"])
    .fillna(municipalities_reconciled["ADM3_EN"])
)

municipalities_reconciled["reconciliation_status"] = (
    municipalities_reconciled["ADM3_PCODE"]
    .map(reconciliation_lookup["reconciliation_status"])
    .fillna("source_verified")
)

In [ ]:
display(
    municipalities_reconciled[
        municipalities_reconciled["ADM3_EN"].isin([
            "Datu Odin Sinsuat (Dinaig)",
            "Datu Piang",
            "Sultan Sa Barongis (Lambayong)"
        ])
    ][
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1450,Datu Odin Sinsuat (Dinaig),PH1908707,1908707000,1908705000,Datu Odin Sinsuat,corrected_psa_verified
1464,Datu Piang,PH1908806,1908806000,1908807000,Datu Piang,corrected_psa_verified
1467,Sultan Sa Barongis (Lambayong),PH1908813,1908813000,1908823000,Sultan Sa Barongis,corrected_psa_verified

In [ ]:
municipalities_master = municipalities_reconciled[
    LGU_COLUMNS
].copy()

municipalities_master["lgu_type"] = "Municipality"

lgu_master = pd.concat(
    [
        municipalities_master,
        component_cities_master,
        huc_master,
        independent_cities_master,
    ],
    ignore_index=True
)

In [ ]:
print("Total LGUs:", len(lgu_master))
print(
    "Unique canonical PSGCs:",
    lgu_master["canonical_psgc_code"].nunique()
)

Total LGUs: 1635
Unique canonical PSGCs: 1633

In [ ]:
duplicate_lgu_psgc = (
    lgu_master[
        lgu_master["canonical_psgc_code"]
        .duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

display(
    duplicate_lgu_psgc[
        [
            "ADM3_EN",
            "lgu_type",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,lgu_type,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1467,Sultan Sa Barongis (Lambayong),Municipality,PH1908813,1908813000,1908823000,Sultan Sa Barongis,corrected_psa_verified
1473,Paglat,Municipality,PH1908823,1908823000,1908823000,Paglat,source_verified
1605,City of Isabela,Highly Urbanized City,PH0909701,PH09901,PH09901,City of Isabela,source_verified
1629,NaN,Independent Component City,NaN,PH09901,PH09901,NaN,source_verified

In [ ]:
print(
    "Duplicate PSGC values:",
    lgu_master["canonical_psgc_code"]
    .value_counts()
    .gt(1)
    .sum()
)

Duplicate PSGC values: 2

In [ ]:
paglat_reconciliation = pd.DataFrame([
    {
        "source_lgu_name": "Paglat",
        "source_admin_code": "PH1908823",
        "source_psgc_code": "1908823000",
        "canonical_lgu_name": "Paglat",
        "canonical_psgc_code": "1908817000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    }
])

psgc_reconciliation = pd.concat(
    [psgc_reconciliation, paglat_reconciliation],
    ignore_index=True
)

In [ ]:
isabela_huc = huc[
    huc["ADM3_EN"].eq("City of Isabela")
].copy()

unnamed_icc = independent_component_cities[
    independent_component_cities["ADM3_EN"].isna()
].copy()

print("City of Isabela geometry:")
print(isabela_huc.geometry.iloc[0].geom_type)
print("Area:", isabela_huc.geometry.iloc[0].area)

print("\nUnnamed ICC geometry:")
print(unnamed_icc.geometry.iloc[0].geom_type)
print("Area:", unnamed_icc.geometry.iloc[0].area)

City of Isabela geometry:
MultiPolygon
Area: 0.01766607697984612

Unnamed ICC geometry:
MultiPolygon
Area: 0.017614251451943123

In [ ]:
isabela_geom = isabela_huc.geometry.iloc[0]
icc_geom = unnamed_icc.geometry.iloc[0]

print("Same geometry:", isabela_geom.equals(icc_geom))
print("ICC within Isabela:", icc_geom.within(isabela_geom))
print("Isabela within ICC:", isabela_geom.within(icc_geom))
print("Intersection area:", isabela_geom.intersection(icc_geom).area)

Same geometry: False
ICC within Isabela: False
Isabela within ICC: False
Intersection area: 0.017567615207241847

In [ ]:
intersection_area = isabela_geom.intersection(icc_geom).area

print(
    "Overlap relative to City of Isabela:",
    intersection_area / isabela_geom.area * 100,
    "%"
)

print(
    "Overlap relative to unnamed ICC:",
    intersection_area / icc_geom.area * 100,
    "%"
)

Overlap relative to City of Isabela: 99.44265060818765 %
Overlap relative to unnamed ICC: 99.73523572756689 %

In [ ]:
huc_master = prepare_city_dataset(
    huc,
    "Highly Urbanized City"
)

In [ ]:
isabela_mask = (
    huc_master["ADM3_EN"] == "City of Isabela"
)

huc_master.loc[
    isabela_mask,
    "canonical_psgc_code"
] = "0990101000"

huc_master.loc[
    isabela_mask,
    "canonical_lgu_name"
] = "City of Isabela"

huc_master.loc[
    isabela_mask,
    "reconciliation_status"
] = "psa_verified"

In [ ]:
duplicate_boundary_records = independent_component_cities[
    independent_component_cities["ADM3_EN"].isna()
].copy()

duplicate_boundary_records["canonical_lgu_name"] = "City of Isabela"
duplicate_boundary_records["canonical_psgc_code"] = "0990101000"
duplicate_boundary_records["reconciliation_status"] = (
    "duplicate_boundary_source"
)
duplicate_boundary_records["reconciliation_source"] = (
    "Spatial overlap with City of Isabela HUC"
)

In [ ]:
independent_cities_master = prepare_city_dataset(
    independent_component_cities[
        independent_component_cities["ADM3_EN"].notna()
    ],
    "Independent Component City"
)

In [ ]:
lgu_master = pd.concat(
    [
        municipalities_master,
        component_cities_master,
        huc_master,
        independent_cities_master,
    ],
    ignore_index=True
)

In [ ]:
duplicate_final = (
    lgu_master[
        lgu_master["canonical_psgc_code"]
        .duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

display(
    duplicate_final[
        [
            "ADM3_EN",
            "lgu_type",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,lgu_type,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1467,Sultan Sa Barongis (Lambayong),Municipality,PH1908813,1908813000,1908823000,Sultan Sa Barongis,corrected_psa_verified
1473,Paglat,Municipality,PH1908823,1908823000,1908823000,Paglat,source_verified

In [ ]:
print(
    lgu_master[
        lgu_master["canonical_psgc_code"]
        .duplicated(keep=False)
    ]["canonical_psgc_code"].unique()
)

<StringArray>
['1908823000']
Length: 1, dtype: str

In [ ]:
display(
    psgc_reconciliation[
        psgc_reconciliation["source_lgu_name"] == "Paglat"
    ]
)

,source_lgu_name,source_admin_code,source_psgc_code,canonical_lgu_name,canonical_psgc_code,reconciliation_status,reconciliation_source
24,Paglat,PH1908823,1908823000,Paglat,1908817000,corrected_psa_verified,PSA PSGC

In [ ]:
display(
    municipalities_reconciled[
        municipalities_reconciled["ADM3_EN"] == "Paglat"
    ][
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1473,Paglat,PH1908823,1908823000,1908823000,Paglat,source_verified

In [ ]:
municipalities_master = municipalities_reconciled[
    LGU_COLUMNS
].copy()

municipalities_master["lgu_type"] = "Municipality"

In [ ]:
lgu_master = pd.concat(
    [
        municipalities_master,
        component_cities_master,
        huc_master,
        independent_cities_master,
    ],
    ignore_index=True
)

In [ ]:
print("Total canonical LGUs:", len(lgu_master))
print(
    "Unique canonical PSGCs:",
    lgu_master["canonical_psgc_code"].nunique()
)

Total canonical LGUs: 1634
Unique canonical PSGCs: 1633

In [ ]:
duplicate_final = (
    lgu_master[
        lgu_master["canonical_psgc_code"].duplicated(keep=False)
    ]
)

display(
    duplicate_final[
        [
            "ADM3_EN",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
        ]
    ]
)

,ADM3_EN,canonical_psgc_code,canonical_lgu_name,reconciliation_status
1467,Sultan Sa Barongis (Lambayong),1908823000,Sultan Sa Barongis,corrected_psa_verified
1473,Paglat,1908823000,Paglat,source_verified

In [ ]:
display(
    psgc_reconciliation[
        psgc_reconciliation["source_lgu_name"] == "Paglat"
    ]
)

,source_lgu_name,source_admin_code,source_psgc_code,canonical_lgu_name,canonical_psgc_code,reconciliation_status,reconciliation_source
24,Paglat,PH1908823,1908823000,Paglat,1908817000,corrected_psa_verified,PSA PSGC

In [ ]:
paglat_reconciliation = pd.DataFrame([
    {
        "source_lgu_name": "Paglat",
        "source_admin_code": "PH1908823",
        "source_psgc_code": "1908823000",
        "canonical_lgu_name": "Paglat",
        "canonical_psgc_code": "1908817000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    }
])

psgc_reconciliation = pd.concat(
    [psgc_reconciliation, paglat_reconciliation],
    ignore_index=True
)

In [ ]:
# ============================================================
# BUILD MUNICIPALITY MASTER
# ============================================================

LGU_COLUMNS = [
    "ADM3_EN",
    "ADM3_PCODE",
    "source_psgc_code",
    "canonical_psgc_code",
    "canonical_lgu_name",
    "reconciliation_status",
    "geometry",
]

municipalities_master = municipalities_reconciled[
    LGU_COLUMNS
].copy()

municipalities_master["lgu_type"] = "Municipality"

print(
    "Municipality records:",
    len(municipalities_master)
)

Municipality records: 1485

In [ ]:
print(psgc_reconciliation.columns.tolist())

['source_lgu_name', 'source_admin_code', 'source_psgc_code', 'canonical_lgu_name', 'canonical_psgc_code', 'reconciliation_status', 'reconciliation_source']

In [ ]:
# ============================================================
# CHECK DUPLICATE CANONICAL PSGCs
# ============================================================

duplicates = (
    municipalities_reconciled[
        municipalities_reconciled[
            "canonical_psgc_code"
        ].duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

print(
    "Municipality records:",
    len(municipalities_reconciled)
)

print(
    "Unique canonical PSGCs:",
    municipalities_reconciled[
        "canonical_psgc_code"
    ].nunique()
)

print(
    "Duplicate rows:",
    len(duplicates)
)

duplicates[
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "canonical_lgu_name",
        "canonical_psgc_code",
        "reconciliation_status"
    ]
]

Municipality records: 1485
Unique canonical PSGCs: 1485
Duplicate rows: 0

Empty DataFrame
Columns: [ADM3_EN, ADM3_PCODE, canonical_lgu_name, canonical_psgc_code, reconciliation_status]
Index: []

In [ ]:
# ============================================================
# BUILD CITY MASTERS
# ============================================================

component_cities_master = prepare_city_dataset(
    component_cities,
    "Component City"
)

huc_master = prepare_city_dataset(
    huc,
    "Highly Urbanized City"
)

# Exclude unnamed duplicate City of Isabela boundary
independent_cities_master = prepare_city_dataset(
    independent_component_cities[
        independent_component_cities["ADM3_EN"].notna()
    ],
    "Independent Component City"
)

print("Component Cities:", len(component_cities_master))
print("HUCs:", len(huc_master))
print("Independent Cities:", len(independent_cities_master))

Component Cities: 110
HUCs: 34
Independent Cities: 5

In [ ]:
# ============================================================
# BUILD FULL LGU MASTER
# ============================================================

lgu_master = pd.concat(
    [
        municipalities_master,
        component_cities_master,
        huc_master,
        independent_cities_master,
    ],
    ignore_index=True
)

print("Total canonical LGUs:", len(lgu_master))
print(
    "Unique canonical PSGCs:",
    lgu_master["canonical_psgc_code"].nunique()
)

Total canonical LGUs: 1634
Unique canonical PSGCs: 1634

In [ ]:
# ============================================================
# FULL LGU PSGC UNIQUENESS CHECK
# ============================================================

duplicate_lgu_psgcs = (
    lgu_master[
        lgu_master[
            "canonical_psgc_code"
        ].duplicated(keep=False)
    ]
    .sort_values("canonical_psgc_code")
)

print("========================================")
print("FULL LGU MASTER PSGC CHECK")
print("========================================")

print(
    "Total LGUs:",
    len(lgu_master)
)

print(
    "Unique canonical PSGCs:",
    lgu_master[
        "canonical_psgc_code"
    ].nunique()
)

print(
    "Duplicate rows:",
    len(duplicate_lgu_psgcs)
)

duplicate_lgu_psgcs[
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "canonical_lgu_name",
        "canonical_psgc_code",
        "lgu_type",
        "reconciliation_status"
    ]
]

========================================
FULL LGU MASTER PSGC CHECK
========================================
Total LGUs: 1634
Unique canonical PSGCs: 1634
Duplicate rows: 0

Empty DataFrame
Columns: [ADM3_EN, ADM3_PCODE, canonical_lgu_name, canonical_psgc_code, lgu_type, reconciliation_status]
Index: []

In [ ]:
# ============================================================
# FULL LGU MASTER — GEOMETRY VALIDATION
# ============================================================

print("========================================")
print("LGU MASTER GEOMETRY VALIDATION")
print("========================================")

print("Total LGUs:", len(lgu_master))
print("Missing geometry:", lgu_master.geometry.isna().sum())
print("Empty geometry:", lgu_master.geometry.is_empty.sum())
print("Invalid geometry:", (~lgu_master.geometry.is_valid).sum())
print("Null geometry:", lgu_master.geometry.isna().sum())

# ============================================================
# GEOMETRY TYPES
# ============================================================

print("\nGeometry types:")

print(
    lgu_master.geometry.geom_type.value_counts()
)

# ============================================================
# CRS CHECK
# ============================================================

print("\nCRS:")
print(lgu_master.crs)

========================================
LGU MASTER GEOMETRY VALIDATION
========================================
Total LGUs: 1634
Missing geometry: 0
Empty geometry: 0
Invalid geometry: 1
Null geometry: 0

Geometry types:
Polygon         1270
MultiPolygon     364
Name: count, dtype: int64

CRS:
EPSG:4326

In [ ]:
# ============================================================
# IDENTIFY INVALID LGU GEOMETRY
# ============================================================

invalid_lgus = lgu_master[
    ~lgu_master.geometry.is_valid
].copy()

invalid_lgus[
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "canonical_lgu_name",
        "canonical_psgc_code",
        "lgu_type",
    ]
]

    ADM3_EN ADM3_PCODE canonical_lgu_name canonical_psgc_code      lgu_type
849  Laoang  PH0804808             Laoang          0804808000  Municipality

In [ ]:
# ============================================================
# GEOMETRY VALIDATION REASON
# ============================================================

from shapely.validation import explain_validity

invalid_lgus["geometry_issue"] = (
    invalid_lgus.geometry.apply(explain_validity)
)

invalid_lgus[
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "canonical_lgu_name",
        "geometry_issue",
    ]
]

,ADM3_EN,ADM3_PCODE,canonical_lgu_name,geometry_issue
849,Laoang,PH0804808,Laoang,Ring Self-intersection[125.057932618 12.459744...

In [ ]:
# ============================================================
# REPAIR INVALID LGU GEOMETRIES
# ============================================================

lgu_master_clean = lgu_master.copy()

# Identify invalid geometries
invalid_mask = ~lgu_master_clean.geometry.is_valid

print(
    "Invalid geometries before repair:",
    invalid_mask.sum()
)

# Repair invalid geometries
lgu_master_clean.loc[
    invalid_mask,
    "geometry"
] = (
    lgu_master_clean.loc[
        invalid_mask,
        "geometry"
    ].make_valid()
)

print(
    "Invalid geometries after repair:",
    (
        ~lgu_master_clean.geometry.is_valid
    ).sum()
)

Invalid geometries before repair: 1
Invalid geometries after repair: 0

In [ ]:
# ============================================================
# POST-REPAIR GEOMETRY VALIDATION
# ============================================================

print("========================================")
print("POST-REPAIR GEOMETRY VALIDATION")
print("========================================")

print(
    "Total LGUs:",
    len(lgu_master_clean)
)

print(
    "Missing geometry:",
    lgu_master_clean.geometry.isna().sum()
)

print(
    "Empty geometry:",
    lgu_master_clean.geometry.is_empty.sum()
)

print(
    "Invalid geometry:",
    (
        ~lgu_master_clean.geometry.is_valid
    ).sum()
)

print("\nGeometry types:")

print(
    lgu_master_clean.geometry.geom_type.value_counts()
)

print("\nCRS:")
print(lgu_master_clean.crs)

========================================
POST-REPAIR GEOMETRY VALIDATION
========================================
Total LGUs: 1634
Missing geometry: 0
Empty geometry: 0
Invalid geometry: 0

Geometry types:
Polygon         1270
MultiPolygon     364
Name: count, dtype: int64

CRS:
EPSG:4326

In [ ]:
# ============================================================
# SILVER LGU SPATIAL DATASET
# ============================================================

silver_lgu = lgu_master_clean[
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "source_psgc_code",
        "canonical_psgc_code",
        "canonical_lgu_name",
        "reconciliation_status",
        "lgu_type",
        "geometry",
    ]
].copy()

print("Silver LGU records:", len(silver_lgu))
print("Silver LGU columns:")
print(silver_lgu.columns.tolist())
print("CRS:", silver_lgu.crs)

Silver LGU records: 1634
Silver LGU columns:
['ADM3_EN', 'ADM3_PCODE', 'source_psgc_code', 'canonical_psgc_code', 'canonical_lgu_name', 'reconciliation_status', 'lgu_type', 'geometry']
CRS: EPSG:4326

In [ ]:
# ============================================================
# SILVER LGU QUALITY CHECK
# ============================================================

print("========================================")
print("SILVER LGU QUALITY CHECK")
print("========================================")

print("Records:", len(silver_lgu))

print(
    "Unique canonical PSGCs:",
    silver_lgu["canonical_psgc_code"].nunique()
)

print(
    "Missing canonical PSGCs:",
    silver_lgu["canonical_psgc_code"].isna().sum()
)

print(
    "Duplicate canonical PSGCs:",
    silver_lgu["canonical_psgc_code"].duplicated().sum()
)

print(
    "Missing geometry:",
    silver_lgu.geometry.isna().sum()
)

print(
    "Empty geometry:",
    silver_lgu.geometry.is_empty.sum()
)

print(
    "Invalid geometry:",
    (~silver_lgu.geometry.is_valid).sum()
)

print("CRS:", silver_lgu.crs)

========================================
SILVER LGU QUALITY CHECK
========================================
Records: 1634
Unique canonical PSGCs: 1634
Missing canonical PSGCs: 0
Duplicate canonical PSGCs: 0
Missing geometry: 0
Empty geometry: 0
Invalid geometry: 0
CRS: EPSG:4326

In [ ]:
# ============================================================
# SILVER ATTRIBUTE COMPLETENESS
# ============================================================

silver_lgu[
    [
        "canonical_psgc_code",
        "canonical_lgu_name",
        "lgu_type",
        "geometry",
    ]
].isna().sum()

canonical_psgc_code    0
canonical_lgu_name     0
lgu_type               0
geometry               0
dtype: int64

In [ ]:
from pathlib import Path

# ============================================================
# SILVER LGU OUTPUT DIRECTORY
# ============================================================

silver_dir = Path("data/raw/lgu_boundaries/silver")
silver_dir.mkdir(parents=True, exist_ok=True)

silver_path = silver_dir / "lgu_spatial.parquet"

print("Silver output path:")
print(silver_path)

Silver output path:
data/raw/lgu_boundaries/silver/lgu_spatial.parquet

In [22]:
print("Municipalities:", len(municipalities))
print("Component Cities:", len(component_cities))
print("HUC:", len(huc))
print("Independent Cities:", len(independent_component_cities))

Municipalities: 1485
Component Cities: 110
HUC: 34
Independent Cities: 6

In [24]:
psgc_reconciliation = pd.DataFrame([
    # Maguindanao del Norte
    {
        "source_lgu_name": "Datu Odin Sinsuat",
        "source_admin_code": "PH1908707",
        "source_psgc_code": "1908707000",
        "canonical_lgu_name": "Datu Odin Sinsuat",
        "canonical_psgc_code": "1908705000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Matanog",
        "source_admin_code": "PH1908709",
        "source_psgc_code": "1908709000",
        "canonical_lgu_name": "Matanog",
        "canonical_psgc_code": "1908707000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Northern Kabuntalan",
        "source_admin_code": "PH1908708",
        "source_psgc_code": "1908708000",
        "canonical_lgu_name": "Northern Kabuntalan",
        "canonical_psgc_code": "1908708000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Parang",
        "source_admin_code": "PH1908710",
        "source_psgc_code": "1908710000",
        "canonical_lgu_name": "Parang",
        "canonical_psgc_code": "1908709000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Sultan Kudarat",
        "source_admin_code": "PH1908711",
        "source_psgc_code": "1908711000",
        "canonical_lgu_name": "Sultan Kudarat",
        "canonical_psgc_code": "1908710000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Sultan Mastura",
        "source_admin_code": "PH1908712",
        "source_psgc_code": "1908712000",
        "canonical_lgu_name": "Sultan Mastura",
        "canonical_psgc_code": "1908711000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Talitay",
        "source_admin_code": "PH1908713",
        "source_psgc_code": "1908713000",
        "canonical_lgu_name": "Talitay",
        "canonical_psgc_code": "1908712000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },

    # Maguindanao del Sur
    {
        "source_lgu_name": "Ampatuan",
        "source_admin_code": "PH1908801",
        "source_psgc_code": "1908801000",
        "canonical_lgu_name": "Ampatuan",
        "canonical_psgc_code": "1908801000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Buluan",
        "source_admin_code": "PH1908802",
        "source_psgc_code": "1908802000",
        "canonical_lgu_name": "Buluan",
        "canonical_psgc_code": "1908802000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Abdullah Sangki",
        "source_admin_code": "PH1908803",
        "source_psgc_code": "1908803000",
        "canonical_lgu_name": "Datu Abdullah Sangki",
        "canonical_psgc_code": "1908803000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Hoffer Ampatuan",
        "source_admin_code": "PH1908805",
        "source_psgc_code": "1908805000",
        "canonical_lgu_name": "Datu Hoffer Ampatuan",
        "canonical_psgc_code": "1908805000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Paglas",
        "source_admin_code": "PH1908805",
        "source_psgc_code": "1908805000",
        "canonical_lgu_name": "Datu Paglas",
        "canonical_psgc_code": "1908806000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Piang",
        "source_admin_code": "PH1908806",
        "source_psgc_code": "1908806000",
        "canonical_lgu_name": "Datu Piang",
        "canonical_psgc_code": "1908807000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Salibo",
        "source_admin_code": "PH1908808",
        "source_psgc_code": "1908808000",
        "canonical_lgu_name": "Datu Salibo",
        "canonical_psgc_code": "1908808000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Saudi Ampatuan",
        "source_admin_code": "PH1908809",
        "source_psgc_code": "1908809000",
        "canonical_lgu_name": "Datu Saudi Ampatuan",
        "canonical_psgc_code": "1908809000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Datu Unsay",
        "source_admin_code": "PH1908810",
        "source_psgc_code": "1908810000",
        "canonical_lgu_name": "Datu Unsay",
        "canonical_psgc_code": "1908810000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Gen. S.K. Pendatun",
        "source_admin_code": "PH1908811",
        "source_psgc_code": "1908811000",
        "canonical_lgu_name": "Gen. S.K. Pendatun",
        "canonical_psgc_code": "1908811000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Mamasapano",
        "source_admin_code": "PH1908820",
        "source_psgc_code": "1908820000",
        "canonical_lgu_name": "Mamasapano",
        "canonical_psgc_code": "1908813000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Pagagawan",
        "source_admin_code": "PH1908822",
        "source_psgc_code": "1908822000",
        "canonical_lgu_name": "Pagagawan",
        "canonical_psgc_code": "1908815000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Pagalungan",
        "source_admin_code": "PH1908816",
        "source_psgc_code": "1908816000",
        "canonical_lgu_name": "Pagalungan",
        "canonical_psgc_code": "1908816000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Paglat",
        "source_admin_code": "PH1908823",
        "source_psgc_code": "1908823000",
        "canonical_lgu_name": "Paglat",
        "canonical_psgc_code": "1908817000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Rajah Buayan",
        "source_admin_code": "PH1908819",
        "source_psgc_code": "1908819000",
        "canonical_lgu_name": "Rajah Buayan",
        "canonical_psgc_code": "1908819000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Shariff Aguak",
        "source_admin_code": "PH1908820",
        "source_psgc_code": "1908820000",
        "canonical_lgu_name": "Shariff Aguak",
        "canonical_psgc_code": "1908820000",
        "reconciliation_status": "source_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "South Upi",
        "source_admin_code": "PH1908817",
        "source_psgc_code": "1908817000",
        "canonical_lgu_name": "South Upi",
        "canonical_psgc_code": "1908822000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Sultan Sa Barongis",
        "source_admin_code": "PH1908813",
        "source_psgc_code": "1908813000",
        "canonical_lgu_name": "Sultan Sa Barongis",
        "canonical_psgc_code": "1908823000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
    {
        "source_lgu_name": "Talayan",
        "source_admin_code": "PH1908816",
        "source_psgc_code": "1908816000",
        "canonical_lgu_name": "Talayan",
        "canonical_psgc_code": "1908824000",
        "reconciliation_status": "corrected_psa_verified",
        "reconciliation_source": "PSA PSGC",
    },
])

In [25]:
print(psgc_reconciliation.shape)
print(
    psgc_reconciliation[
        psgc_reconciliation["source_admin_code"].duplicated(keep=False)
    ][
        [
            "source_lgu_name",
            "source_admin_code",
            "canonical_psgc_code"
        ]
    ]
)

(26, 7)
         source_lgu_name source_admin_code canonical_psgc_code
10  Datu Hoffer Ampatuan         PH1908805          1908805000
11           Datu Paglas         PH1908805          1908806000
17            Mamasapano         PH1908820          1908813000
19            Pagalungan         PH1908816          1908816000
22         Shariff Aguak         PH1908820          1908820000
25               Talayan         PH1908816          1908824000

In [26]:
check_names = [
    "Datu Hoffer Ampatuan",
    "Datu Paglas",
    "Mamasapano",
    "Shariff Aguak",
    "Pagalungan",
    "Talayan",
]

municipalities[
    municipalities["ADM3_EN"].isin(check_names)
][
    ["ADM3_EN", "ADM3_PCODE", "psgc_id"]
]

                   ADM3_EN ADM3_PCODE    psgc_id
1463           Datu Paglas  PH1908805  PH1908805
1466            Pagalungan  PH1908810  PH1908810
1468               Talayan  PH1908816  PH1908816
1471            Mamasapano  PH1908820  PH1908820
1482  Datu Hoffer Ampatuan  PH1908835  PH1908801

In [27]:
maguindanao = municipalities[
    municipalities["ADM3_PCODE"].str.startswith("PH1908", na=False)
].copy()

maguindanao[
    ["ADM3_EN", "ADM3_PCODE", "psgc_id"]
].sort_values("ADM3_PCODE")

                                ADM3_EN ADM3_PCODE    psgc_id
1449                             Buldon  PH1908702  PH1908702
1450         Datu Odin Sinsuat (Dinaig)  PH1908707  PH1908707
1451                            Matanog  PH1908709  PH1908709
1452                             Parang  PH1908711  PH1908711
1453            Sultan Kudarat (Nuling)  PH1908712  PH1908712
1454                Kabuntalan (Tumbao)  PH1908714  PH1908706
1455                                Upi  PH1908715  PH1908713
1456                             Barira  PH1908718  PH1908701
1457                            Talitay  PH1908721  PH1908712
1458                     Sultan Mastura  PH1908724  PH1908711
1459               Datu Blah T. Sinsuat  PH1908730  PH1908704
1460                Northern Kabuntalan  PH1908734  PH1908706
1461                           Ampatuan  PH1908801  PH1908801
1462                             Buluan  PH1908803  PH1908803
1463                        Datu Paglas  PH1908805  PH1908805
1464                         Datu Piang  PH1908806  PH1908806
1465  Shariff Aguak (Maganoy) (Capital)  PH1908808  PH1908808
1466                         Pagalungan  PH1908810  PH1908810
1467     Sultan Sa Barongis (Lambayong)  PH1908813  PH1908813
1468                            Talayan  PH1908816  PH1908816
1469                          South Upi  PH1908817  PH1908817
1470                 Gen. S.K. Pendatun  PH1908819  PH1908819
1471                         Mamasapano  PH1908820  PH1908820
1472                          Pagagawan  PH1908822  PH1908822
1473                             Paglat  PH1908823  PH1908823
1474                       Guindulungan  PH1908825  PH1908812
1475                Datu Saudi-Ampatuan  PH1908826  PH1908801
1476                         Datu Unsay  PH1908827  PH1908810
1477               Datu Abdullah Sangki  PH1908828  PH1908803
1478                       Rajah Buayan  PH1908829  PH1908819
1479             Datu Anggal Midtimbang  PH1908831  PH1908804
1480                        Mangudadatu  PH1908832  PH1908814
1481                             Pandag  PH1908833  PH1908818
1482               Datu Hoffer Ampatuan  PH1908835  PH1908801
1483                        Datu Salibo  PH1908836  PH1908808
1484           Shariff Saydona Mustapha  PH1908837  PH1908821

In [28]:
psa_maguindanao = {
    # Maguindanao del Norte
    "Barira": "1908701000",
    "Buldon": "1908702000",
    "Datu Blah T. Sinsuat": "1908704000",
    "Datu Odin Sinsuat (Dinaig)": "1908705000",
    "Kabuntalan (Tumbao)": "1908706000",
    "Matanog": "1908707000",
    "Northern Kabuntalan": "1908708000",
    "Parang": "1908709000",
    "Sultan Kudarat (Nuling)": "1908710000",
    "Sultan Mastura": "1908711000",
    "Talitay": "1908712000",
    "Upi": "1908713000",

    # Maguindanao del Sur
    "Ampatuan": "1908801000",
    "Buluan": "1908802000",
    "Datu Abdullah Sangki": "1908803000",
    "Datu Anggal Midtimbang": "1908804000",
    "Datu Hoffer Ampatuan": "1908805000",
    "Datu Paglas": "1908806000",
    "Datu Piang": "1908807000",
    "Datu Salibo": "1908808000",
    "Datu Saudi-Ampatuan": "1908809000",
    "Datu Unsay": "1908810000",
    "Gen. S.K. Pendatun": "1908811000",
    "Guindulungan": "1908812000",
    "Mamasapano": "1908813000",
    "Mangudadatu": "1908814000",
    "Pagagawan": "1908815000",
    "Pagalungan": "1908816000",
    "Paglat": "1908817000",
    "Pandag": "1908818000",
    "Rajah Buayan": "1908819000",
    "Shariff Aguak (Maganoy) (Capital)": "1908820000",
    "Shariff Saydona Mustapha": "1908821000",
    "South Upi": "1908822000",
    "Sultan Sa Barongis (Lambayong)": "1908823000",
    "Talayan": "1908824000",
}

In [29]:
maguindanao["canonical_psgc_code"] = (
    maguindanao["ADM3_EN"].map(psa_maguindanao)
)

unmapped = maguindanao[
    maguindanao["canonical_psgc_code"].isna()
][
    ["ADM3_EN", "ADM3_PCODE", "psgc_id"]
]

print("Maguindanao records:", len(maguindanao))
print("Mapped:", maguindanao["canonical_psgc_code"].notna().sum())
print("Unmapped:", len(unmapped))

unmapped

Maguindanao records: 36
Mapped: 36
Unmapped: 0

Empty DataFrame
Columns: [ADM3_EN, ADM3_PCODE, psgc_id]
Index: []

In [30]:
maguindanao["canonical_lgu_name"] = maguindanao["ADM3_EN"]

maguindanao["reconciliation_status"] = (
    maguindanao["psgc_id"]
    .astype(str)
    .eq(maguindanao["canonical_psgc_code"])
    .map({
        True: "source_verified",
        False: "corrected_psa_verified"
    })
)

maguindanao[
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "psgc_id",
        "canonical_psgc_code",
        "reconciliation_status"
    ]
].sort_values("ADM3_EN")

,ADM3_EN,ADM3_PCODE,psgc_id,canonical_psgc_code,reconciliation_status
1461,Ampatuan,PH1908801,PH1908801,1908801000,corrected_psa_verified
1456,Barira,PH1908718,PH1908701,1908701000,corrected_psa_verified
1449,Buldon,PH1908702,PH1908702,1908702000,corrected_psa_verified
1462,Buluan,PH1908803,PH1908803,1908802000,corrected_psa_verified
1477,Datu Abdullah Sangki,PH1908828,PH1908803,1908803000,corrected_psa_verified
1479,Datu Anggal Midtimbang,PH1908831,PH1908804,1908804000,corrected_psa_verified
1459,Datu Blah T. Sinsuat,PH1908730,PH1908704,1908704000,corrected_psa_verified
1482,Datu Hoffer Ampatuan,PH1908835,PH1908801,1908805000,corrected_psa_verified
1450,Datu Odin Sinsuat (Dinaig),PH1908707,PH1908707,1908705000,corrected_psa_verified
1463,Datu Paglas,PH1908805,PH1908805,1908806000,corrected_psa_verified
1464,Datu Piang,PH1908806,PH1908806,1908807000,corrected_psa_verified
1483,Datu Salibo,PH1908836,PH1908808,1908808000,corrected_psa_verified
1475,Datu Saudi-Ampatuan,PH1908826,PH1908801,1908809000,corrected_psa_verified
1476,Datu Unsay,PH1908827,PH1908810,1908810000,corrected_psa_verified
1470,Gen. S.K. Pendatun,PH1908819,PH1908819,1908811000,corrected_psa_verified
1474,Guindulungan,PH1908825,PH1908812,1908812000,corrected_psa_verified
1454,Kabuntalan (Tumbao),PH1908714,PH1908706,1908706000,corrected_psa_verified
1471,Mamasapano,PH1908820,PH1908820,1908813000,corrected_psa_verified
1480,Mangudadatu,PH1908832,PH1908814,1908814000,corrected_psa_verified
1451,Matanog,PH1908709,PH1908709,1908707000,corrected_psa_verified
1460,Northern Kabuntalan,PH1908734,PH1908706,1908708000,corrected_psa_verified
1472,Pagagawan,PH1908822,PH1908822,1908815000,corrected_psa_verified
1466,Pagalungan,PH1908810,PH1908810,1908816000,corrected_psa_verified
1473,Paglat,PH1908823,PH1908823,1908817000,corrected_psa_verified
1481,Pandag,PH1908833,PH1908818,1908818000,corrected_psa_verified
1452,Parang,PH1908711,PH1908711,1908709000,corrected_psa_verified
1478,Rajah Buayan,PH1908829,PH1908819,1908819000,corrected_psa_verified
1465,Shariff Aguak (Maganoy) (Capital),PH1908808,PH1908808,1908820000,corrected_psa_verified
1484,Shariff Saydona Mustapha,PH1908837,PH1908821,1908821000,corrected_psa_verified
1469,South Upi,PH1908817,PH1908817,1908822000,corrected_psa_verified
1453,Sultan Kudarat (Nuling),PH1908712,PH1908712,1908710000,corrected_psa_verified
1458,Sultan Mastura,PH1908724,PH1908711,1908711000,corrected_psa_verified
1467,Sultan Sa Barongis (Lambayong),PH1908813,PH1908813,1908823000,corrected_psa_verified
1468,Talayan,PH1908816,PH1908816,1908824000,corrected_psa_verified
1457,Talitay,PH1908721,PH1908712,1908712000,corrected_psa_verified
1455,Upi,PH1908715,PH1908713,1908713000,corrected_psa_verified

In [31]:
print(
    "Duplicate canonical PSGCs:",
    maguindanao["canonical_psgc_code"].duplicated().sum()
)

print(
    "Unique canonical PSGCs:",
    maguindanao["canonical_psgc_code"].nunique()
)

Duplicate canonical PSGCs: 0
Unique canonical PSGCs: 36

In [32]:
municipalities_reconciled = municipalities.copy()

municipalities_reconciled["source_lgu_name"] = (
    municipalities_reconciled["ADM3_EN"]
)

municipalities_reconciled["source_admin_code"] = (
    municipalities_reconciled["ADM3_PCODE"]
)

municipalities_reconciled["source_psgc_code"] = (
    municipalities_reconciled["psgc_id"]
)

In [33]:
municipalities_reconciled["canonical_psgc_code"] = (
    municipalities_reconciled["psgc_id"]
)

municipalities_reconciled["canonical_lgu_name"] = (
    municipalities_reconciled["ADM3_EN"]
)

municipalities_reconciled["reconciliation_status"] = (
    "source_verified"
)

municipalities_reconciled["reconciliation_source"] = (
    "PSA PSGC"
)

In [34]:
maguindanao_mask = (
    municipalities_reconciled["ADM3_EN"]
    .isin(psa_maguindanao.keys())
)

municipalities_reconciled.loc[
    maguindanao_mask,
    "canonical_psgc_code"
] = (
    municipalities_reconciled.loc[
        maguindanao_mask,
        "ADM3_EN"
    ].map(psa_maguindanao)
)

In [35]:
changed_mask = (
    municipalities_reconciled["source_psgc_code"]
    != municipalities_reconciled["canonical_psgc_code"]
)

municipalities_reconciled.loc[
    changed_mask,
    "reconciliation_status"
] = "corrected_psa_verified"

In [36]:
print("Total municipalities:", len(municipalities_reconciled))

print(
    "Unique canonical PSGCs:",
    municipalities_reconciled["canonical_psgc_code"].nunique()
)

print(
    "Duplicate canonical PSGCs:",
    municipalities_reconciled["canonical_psgc_code"].duplicated().sum()
)

print(
    "Missing canonical PSGCs:",
    municipalities_reconciled["canonical_psgc_code"].isna().sum()
)

Total municipalities: 1485
Unique canonical PSGCs: 1484
Duplicate canonical PSGCs: 1
Missing canonical PSGCs: 0

In [37]:
duplicates = municipalities_reconciled[
    municipalities_reconciled["canonical_psgc_code"].duplicated(keep=False)
][
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "psgc_id",
        "canonical_psgc_code",
        "reconciliation_status"
    ]
].sort_values("canonical_psgc_code")

duplicates

     ADM3_EN ADM3_PCODE    psgc_id canonical_psgc_code   reconciliation_status
1427  Parang  PH1906609  PH1906609          1908709000  corrected_psa_verified
1452  Parang  PH1908711  PH1908711          1908709000  corrected_psa_verified

In [38]:
sulu_parang_mask = (
    (municipalities_reconciled["ADM3_EN"] == "Parang")
    & (municipalities_reconciled["ADM3_PCODE"] == "PH1906609")
)

municipalities_reconciled.loc[
    sulu_parang_mask,
    "canonical_psgc_code"
] = "0906609000"

municipalities_reconciled.loc[
    sulu_parang_mask,
    "canonical_lgu_name"
] = "Parang"

municipalities_reconciled.loc[
    sulu_parang_mask,
    "reconciliation_status"
] = "corrected_psa_verified"

In [39]:
print("Total municipalities:",
      len(municipalities_reconciled))

print("Unique canonical PSGCs:",
      municipalities_reconciled["canonical_psgc_code"].nunique())

print("Duplicate canonical PSGCs:",
      municipalities_reconciled["canonical_psgc_code"].duplicated().sum())

print("Missing canonical PSGCs:",
      municipalities_reconciled["canonical_psgc_code"].isna().sum())

Total municipalities: 1485
Unique canonical PSGCs: 1485
Duplicate canonical PSGCs: 0
Missing canonical PSGCs: 0

In [40]:
LGU_COLUMNS = [
    "ADM3_EN",
    "ADM3_PCODE",
    "source_psgc_code",
    "canonical_psgc_code",
    "canonical_lgu_name",
    "reconciliation_status",
    "geometry",
]

In [41]:
municipalities_master = municipalities_reconciled[
    LGU_COLUMNS
].copy()

municipalities_master["lgu_type"] = "Municipality"

In [42]:
print("Municipality master rows:", len(municipalities_master))
print(
    "Unique canonical PSGCs:",
    municipalities_master["canonical_psgc_code"].nunique()
)
print(
    "Missing geometry:",
    municipalities_master["geometry"].isna().sum()
)

Municipality master rows: 1485
Unique canonical PSGCs: 1485
Missing geometry: 0

In [43]:
def prepare_city_dataset(gdf, lgu_type):
    df = gdf.copy()

    df["source_psgc_code"] = df["psgc_id"]
    df["canonical_psgc_code"] = df["psgc_id"]
    df["canonical_lgu_name"] = df["ADM3_EN"]
    df["reconciliation_status"] = "source_verified"
    df["lgu_type"] = lgu_type

    return df[
        [
            "ADM3_EN",
            "ADM3_PCODE",
            "source_psgc_code",
            "canonical_psgc_code",
            "canonical_lgu_name",
            "reconciliation_status",
            "lgu_type",
            "geometry",
        ]
    ]

In [44]:
component_cities_master = prepare_city_dataset(
    component_cities,
    "Component City"
)

huc_master = prepare_city_dataset(
    huc,
    "Highly Urbanized City"
)

independent_cities_master = prepare_city_dataset(
    independent_component_cities[
        independent_component_cities["ADM3_EN"].notna()
    ],
    "Independent Component City"
)

In [45]:
print("Component Cities:", len(component_cities_master))
print("HUC:", len(huc_master))
print("Independent Cities:", len(independent_cities_master))

Component Cities: 110
HUC: 34
Independent Cities: 5

In [46]:
print(
    "Component City duplicate PSGCs:",
    component_cities_master["canonical_psgc_code"].duplicated().sum()
)

print(
    "HUC duplicate PSGCs:",
    huc_master["canonical_psgc_code"].duplicated().sum()
)

print(
    "ICC duplicate PSGCs:",
    independent_cities_master["canonical_psgc_code"].duplicated().sum()
)

Component City duplicate PSGCs: 0
HUC duplicate PSGCs: 0
ICC duplicate PSGCs: 0

In [47]:
isabela_mask = huc_master["ADM3_EN"] == "City of Isabela"

huc_master.loc[
    isabela_mask,
    "canonical_psgc_code"
] = "0990101000"

huc_master.loc[
    isabela_mask,
    "canonical_lgu_name"
] = "City of Isabela"

huc_master.loc[
    isabela_mask,
    "reconciliation_status"
] = "psa_verified"

In [48]:
huc_master[
    huc_master["ADM3_EN"] == "City of Isabela"
][
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "source_psgc_code",
        "canonical_psgc_code",
        "canonical_lgu_name",
        "reconciliation_status"
    ]
]

,ADM3_EN,ADM3_PCODE,source_psgc_code,canonical_psgc_code,canonical_lgu_name,reconciliation_status
10,City of Isabela,PH0909701,PH09901,0990101000,City of Isabela,psa_verified

In [51]:
lgu_master = pd.concat(
    [
        municipalities_master,
        component_cities_master,
        huc_master,
        independent_cities_master,
    ],
    ignore_index=True
)

print("Total LGUs:", len(lgu_master))

print(
    "Unique canonical PSGCs:",
    lgu_master["canonical_psgc_code"].nunique()
)

print(
    "Duplicate canonical PSGCs:",
    lgu_master["canonical_psgc_code"].duplicated().sum()
)

print(
    "Missing canonical PSGCs:",
    lgu_master["canonical_psgc_code"].isna().sum()
)

Total LGUs: 1634
Unique canonical PSGCs: 1634
Duplicate canonical PSGCs: 0
Missing canonical PSGCs: 0

In [52]:
print("Total LGUs:", len(lgu_master))
print("Missing geometry:", lgu_master.geometry.isna().sum())
print("Empty geometry:", lgu_master.geometry.is_empty.sum())
print("Invalid geometry:", (~lgu_master.geometry.is_valid).sum())
print("CRS:", lgu_master.crs)

print("\nGeometry types:")
print(lgu_master.geometry.geom_type.value_counts())

Total LGUs: 1634
Missing geometry: 0
Empty geometry: 0
Invalid geometry: 1
CRS: EPSG:4326

Geometry types:
Polygon         1270
MultiPolygon     364
Name: count, dtype: int64

In [53]:
invalid_lgus = lgu_master[
    ~lgu_master.geometry.is_valid
].copy()

invalid_lgus[
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "canonical_psgc_code",
        "lgu_type"
    ]
]

    ADM3_EN ADM3_PCODE canonical_psgc_code      lgu_type
849  Laoang  PH0804808           PH0804808  Municipality

In [54]:
from shapely.validation import explain_validity

for _, row in invalid_lgus.iterrows():
    print(row["ADM3_EN"])
    print(explain_validity(row.geometry))

Laoang
Ring Self-intersection[125.057932618 12.4597442780001]

In [56]:
lgu_master_clean = lgu_master.copy()

invalid_mask = ~lgu_master_clean.geometry.is_valid

lgu_master_clean.loc[invalid_mask, "geometry"] = (
    lgu_master_clean.loc[invalid_mask, "geometry"].make_valid()
)

print("Invalid geometries:",
      (~lgu_master_clean.geometry.is_valid).sum())

print("Empty geometries:",
      lgu_master_clean.geometry.is_empty.sum())

print("Missing geometries:",
      lgu_master_clean.geometry.isna().sum())

Invalid geometries: 0
Empty geometries: 0
Missing geometries: 0

In [57]:
silver_lgu = lgu_master_clean[
    [
        "ADM3_EN",
        "ADM3_PCODE",
        "source_psgc_code",
        "canonical_psgc_code",
        "canonical_lgu_name",
        "reconciliation_status",
        "lgu_type",
        "geometry",
    ]
].copy()

In [58]:
print("Silver rows:", len(silver_lgu))

print("\nMissing values:")
print(
    silver_lgu[
        [
            "canonical_psgc_code",
            "canonical_lgu_name",
            "lgu_type",
            "geometry",
        ]
    ].isna().sum()
)

Silver rows: 1634

Missing values:
canonical_psgc_code    0
canonical_lgu_name     0
lgu_type               0
geometry               0
dtype: int64

In [59]:
silver_dir = project_root / "data" / "raw" / "lgu_boundaries" / "silver"
silver_dir.mkdir(parents=True, exist_ok=True)

silver_path = silver_dir / "lgu_spatial.parquet"

silver_lgu.to_parquet(
    silver_path,
    index=False
)

print("Saved to:")
print(silver_path)

Saved to:
/mnt/c/Users/allea/Downloads/Ahon Pipeline/AHON-Pipeline/data/raw/lgu_boundaries/silver/lgu_spatial.parquet

In [60]:
silver_check = gpd.read_parquet(silver_path)

print("Rows:", len(silver_check))
print("CRS:", silver_check.crs)
print("Geometry column:", silver_check.geometry.name)

print("\nGeometry validity:")
print("Invalid:", (~silver_check.geometry.is_valid).sum())
print("Empty:", silver_check.geometry.is_empty.sum())
print("Missing:", silver_check.geometry.isna().sum())

print("\nUnique canonical PSGCs:",
      silver_check["canonical_psgc_code"].nunique())

print("Duplicate canonical PSGCs:",
      silver_check["canonical_psgc_code"].duplicated().sum())

Rows: 1634
CRS: {"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type": "GeographicCRS", "name": "WGS 84", "datum_ensemble": {"name": "World Geodetic System 1984 ensemble", "members": [{"name": "World Geodetic System 1984 (Transit)"}, {"name": "World Geodetic System 1984 (G730)"}, {"name": "World Geodetic System 1984 (G873)"}, {"name": "World Geodetic System 1984 (G1150)"}, {"name": "World Geodetic System 1984 (G1674)"}, {"name": "World Geodetic System 1984 (G1762)"}, {"name": "World Geodetic System 1984 (G2139)"}, {"name": "World Geodetic System 1984 (G2296)"}], "ellipsoid": {"name": "WGS 84", "semi_major_axis": 6378137, "inverse_flattening": 298.257223563}, "accuracy": "2.0", "id": {"authority": "EPSG", "code": 6326}}, "coordinate_system": {"subtype": "ellipsoidal", "axis": [{"name": "Geodetic latitude", "abbreviation": "Lat", "direction": "north", "unit": "degree"}, {"name": "Geodetic longitude", "abbreviation": "Lon", "direction": "east", "unit": "degree"}]}, "scope": "Horizontal component of 3D system.", "area": "World.", "bbox": {"south_latitude": -90, "west_longitude": -180, "north_latitude": 90, "east_longitude": 180}, "id": {"authority": "EPSG", "code": 4326}}
Geometry column: geometry

Geometry validity:
Invalid: 0
Empty: 0
Missing: 0

Unique canonical PSGCs: 1634
Duplicate canonical PSGCs: 0